In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/ShopAssist")
POLICY_DIR = PROJECT_DIR / "data" / "policies"
EVALUATION_DIR = PROJECT_DIR / "data" / "evaluation"

assert PROJECT_DIR.exists(), "ShopAssist project folder not found."
assert POLICY_DIR.exists(), "Policy folder not found."

policy_files = sorted(POLICY_DIR.glob("*.md"))

print("Project:", PROJECT_DIR)
print("Policy documents:", len(policy_files))
print("Evaluation folder exists:", EVALUATION_DIR.exists())

Project: /content/drive/MyDrive/ShopAssist
Policy documents: 15
Evaluation folder exists: True

In [3]:
print("Policy files:")
for file in policy_files:
    print("-", file.name)

print("\nSaved evaluation files:")
for file in sorted(EVALUATION_DIR.glob("*.csv")):
    print("-", file.name)

Policy files:
- account_policy.md
- cancellation_policy.md
- damaged_items.md
- delivery_policy.md
- discount_policy.md
- gift_cards.md
- international_shipping.md
- missing_items.md
- payment_policy.md
- privacy_policy.md
- refund_policy.md
- replacement_policy.md
- returns_policy.md
- shipping_policy.md
- warranty_policy.md

Saved evaluation files:
- evaluation_questions.csv
- human_review_benchmark.csv
- human_review_metrics.csv
- improved_evaluation_report.csv
- rag_evaluation_results.csv

In [4]:
# Install the retrieval libraries if needed
%pip install -q sentence-transformers faiss-cpu

In [5]:
import pandas as pd
import numpy as np
import faiss

from sentence_transformers import SentenceTransformer

# Load the existing policy documents
documents = []

for file_path in sorted(POLICY_DIR.glob("*.md")):
    documents.append({
        "source": file_path.name,
        "text": file_path.read_text(encoding="utf-8")
    })

documents_df = pd.DataFrame(documents)

# Load the same embedding model as the original notebook
embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

# Create embeddings for the policy documents
document_embeddings = embedding_model.encode(
    documents_df["text"].tolist(),
    convert_to_numpy=True,
    normalize_embeddings=True
)

# Build the FAISS similarity-search index
index = faiss.IndexFlatIP(document_embeddings.shape[1])
index.add(document_embeddings.astype("float32"))

print("Retrieval system loaded successfully.")
print("Policy documents:", len(documents_df))
print("Embedding shape:", document_embeddings.shape)
print("FAISS index size:", index.ntotal)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Retrieval system loaded successfully.
Policy documents: 15
Embedding shape: (15, 384)
FAISS index size: 15

In [6]:
def search_policies(query, top_k=3):
    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    ).astype("float32")

    scores, indices = index.search(query_embedding, top_k)

    return pd.DataFrame([
        {
            "rank": rank,
            "source": documents_df.iloc[idx]["source"],
            "similarity": round(float(score), 4)
        }
        for rank, (score, idx) in enumerate(
            zip(scores[0], indices[0]), start=1
        )
        if idx >= 0
    ])


search_policies("What if my item arrived broken?")

   rank                 source  similarity
0     1       damaged_items.md      0.6734
1     2       missing_items.md      0.5790
2     3  replacement_policy.md      0.5411

In [7]:
from google.colab import userdata
from google import genai

GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")
assert GEMINI_API_KEY, "Add GEMINI_API_KEY to Colab Secrets."

client = genai.Client(api_key=GEMINI_API_KEY)

print("Gemini client configured.")

Gemini client configured.

In [8]:

# Conversation memory
conversation_history = []


def add_to_memory(user_message, assistant_message):
    """Store a customer-assistant exchange."""
    conversation_history.append({
        "role": "user",
        "content": user_message
    })
    conversation_history.append({
        "role": "assistant",
        "content": assistant_message
    })


def resolve_follow_up_query(query):
    """Add recent customer context to likely follow-up questions."""
    follow_up_starters = (
        "what about", "what if", "how about",
        "and if", "what happens if", "can they",
        "will they", "can i do that"
    )

    query_lower = query.lower().strip()

    if query_lower.startswith(follow_up_starters):
        previous_questions = [
            item["content"]
            for item in conversation_history[-6:]
            if item["role"] == "user"
        ]

        if previous_questions:
            return (
                "Previous customer context: "
                + " ".join(previous_questions[-2:])
                + ". Current follow-up question: "
                + query
            )

    return query


def chat_with_shopassist(user_message, top_k=3):
    """Generate a policy-grounded answer and store the exchange."""

    # Retrieve policies using the current question and relevant context
    resolved_query = resolve_follow_up_query(user_message)
    retrieved = search_policies(resolved_query, top_k=top_k)

    # Prepare policy context
    context_parts = []

    for _, row in retrieved.iterrows():
        policy_text = documents_df.loc[
            documents_df["source"] == row["source"], "text"
        ].iloc[0]

        context_parts.append(
            f"Source: {row['source']}\n{policy_text}"
        )

    context = "\n\n---\n\n".join(context_parts)

    # Include recent conversation history
    history_text = "\n".join(
        f"{item['role'].capitalize()}: {item['content']}"
        for item in conversation_history[-6:]
    )

    prompt = f"""
You are ShopAssist AI, an e-commerce customer support assistant.

Rules:
- Answer using only the supplied policy information.
- Use conversation history to understand follow-up questions.
- Do not invent policies or promise outcomes.
- If the policies do not answer the question, say the information
  is unavailable.
- Be concise, helpful, and professional.
- Mention relevant policy filenames when appropriate.

CONVERSATION HISTORY:
{history_text if history_text else "No previous conversation."}

RELEVANT POLICIES:
{context}

CUSTOMER QUESTION:
{user_message}

ANSWER:
"""

    # One Gemini API request
    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt
    )

    answer = response.text or (
        "I'm sorry, I couldn't generate a response. Please try again."
    )

    # Save only after a response has been generated
    add_to_memory(user_message, answer)

    return {
        "answer": answer,
        "retrieved_documents": retrieved
    }


print("ShopAssist chatbot functions are ready.")

ShopAssist chatbot functions are ready.

In [9]:
def chat_with_shopassist(user_message, top_k=3):
    """Answer a customer using retrieved policies and recent chat history."""

    # Resolve the question using previous conversation
    resolved_query = resolve_follow_up_query(user_message)

    # Retrieve relevant policy documents
    retrieved = search_policies(resolved_query, top_k=top_k)

    # Build policy context
    context_parts = []

    for _, row in retrieved.iterrows():
        policy_text = documents_df.loc[
            documents_df["source"] == row["source"], "text"
        ].iloc[0]

        context_parts.append(
            f"Source: {row['source']}\n{policy_text}"
        )

    context = "\n\n---\n\n".join(context_parts)

    # Include recent conversation
    history_text = "\n".join(
        f"{message['role'].capitalize()}: {message['content']}"
        for message in conversation_history[-6:]
    )

    prompt = f"""
You are ShopAssist AI, an e-commerce customer support assistant.

Rules:
- Answer using only the policy information provided.
- Use conversation history to understand follow-up questions.
- Never invent policy details or promise an outcome not stated in a policy.
- If the policies do not answer the question, say the information is unavailable.
- Give a concise, helpful response.
- Mention the relevant policy filename when appropriate.

CONVERSATION HISTORY:
{history_text if history_text else "No previous conversation."}

RELEVANT POLICIES:
{context}

CURRENT CUSTOMER QUESTION:
{user_message}

ANSWER:
"""

    # Call Gemini only when this function is explicitly run
    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt
    )

    answer = response.text or (
        "I'm sorry, I couldn't generate a response just now. Please try again."
    )

    # Store the original customer question and the generated answer
    add_to_memory(user_message, answer)

    return {
        "answer": answer,
        "retrieved_documents": retrieved
    }

In [10]:
result = chat_with_shopassist(
    "My item arrived damaged. What should I do?"
)

print("ShopAssist AI:")
print(result["answer"])

print("\nRetrieved policies:")
display(result["retrieved_documents"])

ShopAssist AI:
You should contact support as soon as possible. Please note that you may be asked to provide photographs of the damaged product, the packaging, and the shipping label. Additionally, you should not dispose of the damaged product or packaging until support has advised you to do so (damaged_items.md). You may also request a replacement within 30 days of delivery (replacement_policy.md).

Retrieved policies:

   rank                 source  similarity
0     1       damaged_items.md      0.6573
1     2       missing_items.md      0.4786
2     3  replacement_policy.md      0.4662

In [11]:
%pip install -q gradio

In [12]:
import gradio as gr


def respond(message, history):
    """Send a customer message to ShopAssist and return its answer."""

    if not message or not message.strip():
        return "Please enter a question."

    try:
        result = chat_with_shopassist(message.strip())
        return result["answer"]

    except Exception as error:
        error_text = str(error).lower()

        if "429" in error_text or "resource_exhausted" in error_text:
            return (
                "I'm temporarily unable to generate a response because "
                "the AI service has reached its usage limit. Please try "
                "again later."
            )

        print("Chatbot error:", repr(error))
        return (
            "Sorry, something went wrong while processing your question. "
            "Please try again later."
        )


demo = gr.ChatInterface(
    fn=respond,
    title="ShopAssist AI",
    description=(
        "Your e-commerce customer support assistant. "
        "Ask about delivery, returns, refunds, replacements, and more."
    ),
    examples=[
        "How long does standard delivery take?",
        "How can I return an item?",
        "My item arrived damaged. What should I do?",
        "What payment methods do you accept?"
    ]
)

demo.launch(share=True, debug=True)

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://0fe6f8808dd44ca8c8.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://0fe6f8808dd44ca8c8.gradio.live

In [13]:
import gradio as gr


def respond(message, history):
    """Answer using this Gradio session's conversation history."""

    message = message.strip()
    if not message:
        return "Please enter a question."

    # Keep only recent messages from this user's current chat.
    recent_history = history[-6:] if history else []

    # Support Gradio message dictionaries and older tuple-style history.
    history_lines = []
    previous_user_messages = []

    for item in recent_history:
        if isinstance(item, dict):
            role = item.get("role", "")
            content = item.get("content", "")
            if isinstance(content, str) and role in ("user", "assistant"):
                history_lines.append(f"{role.capitalize()}: {content}")
                if role == "user":
                    previous_user_messages.append(content)

        elif isinstance(item, (list, tuple)) and len(item) == 2:
            user_text, assistant_text = item
            if user_text:
                history_lines.append(f"User: {user_text}")
                previous_user_messages.append(str(user_text))
            if assistant_text:
                history_lines.append(f"Assistant: {assistant_text}")

    # Use prior context for likely follow-up questions.
    follow_up_starters = (
        "what about", "what if", "how about", "and if",
        "can they", "will they", "what happens if",
        "what should i do", "can i do that"
    )

    is_follow_up = message.lower().startswith(follow_up_starters)

    if is_follow_up and previous_user_messages:
        retrieval_query = (
            "Previous customer context: "
            + " ".join(previous_user_messages[-2:])
            + ". Current question: "
            + message
        )
    else:
        retrieval_query = message

    retrieved = search_policies(retrieval_query, top_k=3)

    policy_context = []

    for _, row in retrieved.iterrows():
        policy_text = documents_df.loc[
            documents_df["source"] == row["source"], "text"
        ].iloc[0]

        policy_context.append(
            f"Source: {row['source']}\n{policy_text}"
        )

    prompt = f"""
You are ShopAssist AI, an e-commerce customer support assistant.

Answer using only the policy information below.
Use the conversation history to understand follow-up questions.
Do not invent policy rules or promise outcomes.
If the policies do not answer the question, say so clearly.
Give a concise, helpful answer and cite the relevant policy filename.

CONVERSATION HISTORY:
{chr(10).join(history_lines) if history_lines else "No previous conversation."}

RELEVANT POLICIES:
{"".join(policy_context)}

CURRENT CUSTOMER QUESTION:
{message}

ANSWER:
"""

    try:
        response = client.models.generate_content(
            model="gemini-3.5-flash-lite",
            contents=prompt
        )

        answer = response.text

        if not answer:
            return "I couldn't generate an answer just now. Please try again later."

        return answer

    except Exception as error:
        error_text = str(error).lower()

        if "429" in error_text or "resource_exhausted" in error_text:
            return (
                "The AI service has reached its current usage limit. "
                "Please try again later."
            )

        print("Chatbot error:", repr(error))
        return "Sorry, something went wrong. Please try again later."


demo = gr.ChatInterface(
    fn=respond,
    title="ShopAssist AI",
    description=(
        "Your e-commerce customer support assistant. "
        "Ask about delivery, returns, refunds, and replacements."
    ),
    examples=[
        "How long does standard delivery take?",
        "How can I return an item?",
        "My item arrived damaged. What should I do?"
    ]
)

print("Session-aware chatbot interface is ready.")

Session-aware chatbot interface is ready.

In [14]:
demo.launch(share=True, debug=True)

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://b349cf130b564ccee1.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://b349cf130b564ccee1.gradio.live

In [15]:

for folder in ["src", "app", "tests", "data/policies", "data/evaluation"]:
    path = PROJECT_DIR / folder
    print(f"\n{folder}/")

    if path.exists():
        for item in sorted(path.iterdir()):
            print("  ", item.name)
    else:
        print("   Folder does not exist")

src/
   __pycache__
   chatbot.py
   retrieval.py

app/
   gradio_app.py

tests/
   test_retrieval.py

data/policies/
   account_policy.md
   cancellation_policy.md
   damaged_items.md
   delivery_policy.md
   discount_policy.md
   gift_cards.md
   international_shipping.md
   missing_items.md
   payment_policy.md
   privacy_policy.md
   refund_policy.md
   replacement_policy.md
   returns_policy.md
   shipping_policy.md
   warranty_policy.md

data/evaluation/
   evaluation_questions.csv
   evaluation_questions.gsheet
   human_review_benchmark.csv
   human_review_benchmark.gsheet
   human_review_metrics.csv
   improved_evaluation_report.csv
   rag_evaluation_results.csv

In [16]:
from pathlib import Path

retrieval_code = r'''
from pathlib import Path

import faiss
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer


def load_policies(policy_dir):
    """Load all Markdown policy files from a directory."""
    policy_dir = Path(policy_dir)
    documents = []

    for file_path in sorted(policy_dir.glob("*.md")):
        documents.append({
            "source": file_path.name,
            "text": file_path.read_text(encoding="utf-8")
        })

    if not documents:
        raise ValueError(f"No Markdown policy files found in {policy_dir}")

    return pd.DataFrame(documents)


def build_retrieval_index(documents_df, model_name="sentence-transformers/all-MiniLM-L6-v2"):
    """Create normalized embeddings and a FAISS similarity-search index."""
    model = SentenceTransformer(model_name)

    embeddings = model.encode(
        documents_df["text"].tolist(),
        convert_to_numpy=True,
        normalize_embeddings=True,
        show_progress_bar=True
    ).astype("float32")

    index = faiss.IndexFlatIP(embeddings.shape[1])
    index.add(embeddings)

    return model, index


def search_policies(query, documents_df, model, index, top_k=3):
    """Return the top matching policy documents and similarity scores."""
    if not query or not query.strip():
        return pd.DataFrame(columns=["rank", "source", "similarity"])

    query_embedding = model.encode(
        [query.strip()],
        convert_to_numpy=True,
        normalize_embeddings=True
    ).astype("float32")

    k = min(top_k, len(documents_df))
    scores, indices = index.search(query_embedding, k)

    results = []
    for rank, (score, idx) in enumerate(
        zip(scores[0], indices[0]), start=1
    ):
        if idx >= 0:
            results.append({
                "rank": rank,
                "source": documents_df.iloc[idx]["source"],
                "similarity": float(score)
            })

    return pd.DataFrame(results)
'''

project_src = PROJECT_DIR / "src"
project_src.mkdir(parents=True, exist_ok=True)

retrieval_file = project_src / "retrieval.py"
retrieval_file.write_text(retrieval_code.strip() + "\n", encoding="utf-8")

print("Created:", retrieval_file)
print("File size:", retrieval_file.stat().st_size, "bytes")

Created: /content/drive/MyDrive/ShopAssist/src/retrieval.py
File size: 1949 bytes

In [17]:
import sys

if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

from src.retrieval import (
    load_policies,
    build_retrieval_index,
    search_policies
)

test_documents = load_policies(PROJECT_DIR / "data" / "policies")
test_model, test_index = build_retrieval_index(test_documents)

test_results = search_policies(
    "My item arrived damaged. What should I do?",
    test_documents,
    test_model,
    test_index,
    top_k=3
)

print("Policies loaded:", len(test_documents))
display(test_results)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Policies loaded: 15

   rank                 source  similarity
0     1       damaged_items.md    0.657310
1     2       missing_items.md    0.478592
2     3  replacement_policy.md    0.466196

In [18]:
chatbot_code = r'''
import os

from google import genai

from src.retrieval import search_policies


def create_chatbot(
    documents_df,
    embedding_model,
    faiss_index,
    api_key=None,
    model_name="gemini-3.5-flash-lite"
):
    """Create a policy-grounded ShopAssist chatbot."""

    api_key = api_key or os.environ.get("GEMINI_API_KEY")

    if not api_key:
        raise ValueError(
            "Gemini API key not found. Pass api_key explicitly."
        )

    client = genai.Client(api_key=api_key)

    def answer_question(question, history=None):
        if not question or not question.strip():
            return "Please enter a question."

        history = history or []

        # Retrieve relevant policies
        results = search_policies(
            question,
            documents_df,
            embedding_model,
            faiss_index,
            top_k=3
        )

        policy_context = []

        for _, row in results.iterrows():
            policy_text = documents_df.loc[
                documents_df["source"] == row["source"],
                "text"
            ].iloc[0]

            policy_context.append(
                f"Source: {row['source']}\n{policy_text}"
            )

        context_text = "\n\n".join(policy_context)

        # Keep only recent conversation turns
        history_text = ""
        for item in history[-6:]:
            if isinstance(item, dict):
                role = item.get("role", "")
                content = item.get("content", "")
                if role in ("user", "assistant") and isinstance(content, str):
                    history_text += f"{role.capitalize()}: {content}\n"
            elif isinstance(item, (list, tuple)) and len(item) == 2:
                user_text, assistant_text = item
                if user_text:
                    history_text += f"User: {user_text}\n"
                if assistant_text:
                    history_text += f"Assistant: {assistant_text}\n"

        prompt = f"""
You are ShopAssist AI, an e-commerce customer support assistant.

Answer the customer's question using only the supplied policy documents.
Use the conversation history to understand follow-up questions.

Rules:
1. Do not invent policies, deadlines, exceptions, or guarantees.
2. If the policies do not answer the question, clearly say that the
   available policies do not specify the answer.
3. Give clear, concise, helpful next steps when supported by the policies.
4. Cite the relevant policy filenames in your answer, for example:
   (Source: returns_policy.md).
5. Do not claim an action has been completed or that you contacted support.
6. Never ask the customer to provide passwords or full card numbers.

Relevant policy documents:
{context_text}

Recent conversation:
{history_text if history_text else "No previous conversation."}

Current customer question:
{question.strip()}
"""

        try:
            response = client.models.generate_content(
                model=model_name,
                contents=prompt
            )

            answer = response.text

            if not answer:
                return "I couldn't generate an answer. Please try again."

            return answer

        except Exception as error:
            error_text = str(error).lower()

            if "429" in error_text or "resource_exhausted" in error_text:
                return (
                    "The AI service has reached its current usage limit. "
                    "Please try again later."
                )

            return (
                "Sorry, I couldn't process your question right now. "
                "Please try again later."
            )

    return answer_question
'''

chatbot_file = PROJECT_DIR / "src" / "chatbot.py"
chatbot_file.write_text(chatbot_code.strip() + "\n", encoding="utf-8")

print("Created:", chatbot_file)
print("File size:", chatbot_file.stat().st_size, "bytes")

Created: /content/drive/MyDrive/ShopAssist/src/chatbot.py
File size: 3684 bytes

In [19]:
from google.colab import userdata
from src.chatbot import create_chatbot

# Retrieve the API key securely from Colab Secrets
gemini_key = userdata.get("GEMINI_API_KEY")

# Initialise the chatbot using the retrieval objects from Step 2
shopassist = create_chatbot(
    documents_df=test_documents,
    embedding_model=test_model,
    faiss_index=test_index,
    api_key=gemini_key
)

print("ShopAssist chatbot initialised successfully!")
print("Policy documents available:", len(test_documents))

ShopAssist chatbot initialised successfully!
Policy documents available: 15

In [20]:
app_dir = PROJECT_DIR / "app"
app_dir.mkdir(parents=True, exist_ok=True)

print("App folder:", app_dir)
print("Chatbot module exists:", (PROJECT_DIR / "src" / "chatbot.py").exists())
print("Retrieval module exists:", (PROJECT_DIR / "src" / "retrieval.py").exists())

App folder: /content/drive/MyDrive/ShopAssist/app
Chatbot module exists: True
Retrieval module exists: True

In [21]:
app_code = r'''
from pathlib import Path
import sys

import gradio as gr
from google.colab import userdata

# Locate the project root
PROJECT_DIR = Path("/content/drive/MyDrive/ShopAssist")

if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

from src.retrieval import (
    load_policies,
    build_retrieval_index
)
from src.chatbot import create_chatbot


def build_app():
    """Build the ShopAssist customer-support chat interface."""

    policy_dir = PROJECT_DIR / "data" / "policies"
    documents_df = load_policies(policy_dir)

    embedding_model, faiss_index = build_retrieval_index(documents_df)

    api_key = userdata.get("GEMINI_API_KEY")

    chatbot = create_chatbot(
        documents_df=documents_df,
        embedding_model=embedding_model,
        faiss_index=faiss_index,
        api_key=api_key
    )

    def respond(message, history):
        if not message or not message.strip():
            return "Please enter a question."

        try:
            return chatbot(message.strip(), history=history)
        except Exception:
            return (
                "Sorry, something went wrong. "
                "Please try asking your question again."
            )

    demo = gr.ChatInterface(
        fn=respond,
        title="ShopAssist AI",
        description=(
            "Your e-commerce support assistant. "
            "Ask about delivery, returns, refunds, replacements, and more. "
            "Answers are grounded in the available policy documents."
        ),
        examples=[
            "How long does standard delivery take?",
            "How can I return an item?",
            "My item arrived damaged. What should I do?",
            "Can I cancel my order after dispatch?"
        ]
    )

    return demo


if __name__ == "__main__":
    app = build_app()
    app.launch(share=True)
'''

app_dir = PROJECT_DIR / "app"
app_dir.mkdir(parents=True, exist_ok=True)

app_file = app_dir / "gradio_app.py"
app_file.write_text(app_code.strip() + "\n", encoding="utf-8")

print("Created:", app_file)
print("File size:", app_file.stat().st_size, "bytes")

Created: /content/drive/MyDrive/ShopAssist/app/gradio_app.py
File size: 1851 bytes

In [22]:
app_file = PROJECT_DIR / "app" / "gradio_app.py"

print("Application file exists:", app_file.exists())
print("File size:", app_file.stat().st_size, "bytes")
print("\nFirst 15 lines:\n")

print("\n".join(app_file.read_text(encoding="utf-8").splitlines()[:15]))

Application file exists: True
File size: 1851 bytes

First 15 lines:

from pathlib import Path
import sys

import gradio as gr
from google.colab import userdata

# Locate the project root
PROJECT_DIR = Path("/content/drive/MyDrive/ShopAssist")

if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

from src.retrieval import (
    load_policies,
    build_retrieval_index

In [23]:
requirements = """sentence-transformers
faiss-cpu
numpy
pandas
google-genai
gradio
"""

requirements_file = PROJECT_DIR / "requirements.txt"
requirements_file.write_text(requirements, encoding="utf-8")

print("Created:", requirements_file)
print("\nDependencies:")
print(requirements_file.read_text(encoding="utf-8"))

Created: /content/drive/MyDrive/ShopAssist/requirements.txt

Dependencies:
sentence-transformers
faiss-cpu
numpy
pandas
google-genai
gradio

In [24]:
for folder in [
    "src",
    "app",
    "tests",
    "data/policies",
    "data/evaluation"
]:
    path = PROJECT_DIR / folder
    print(f"\n{folder}/")

    for item in sorted(path.iterdir()):
        if item.is_file():
            print("  ", item.name)

print("\nRoot-level files:")
for item in sorted(PROJECT_DIR.iterdir()):
    if item.is_file():
        print("  ", item.name)

src/
   chatbot.py
   retrieval.py

app/
   gradio_app.py

tests/
   test_retrieval.py

data/policies/
   account_policy.md
   cancellation_policy.md
   damaged_items.md
   delivery_policy.md
   discount_policy.md
   gift_cards.md
   international_shipping.md
   missing_items.md
   payment_policy.md
   privacy_policy.md
   refund_policy.md
   replacement_policy.md
   returns_policy.md
   shipping_policy.md
   warranty_policy.md

data/evaluation/
   evaluation_questions.csv
   evaluation_questions.gsheet
   human_review_benchmark.csv
   human_review_benchmark.gsheet
   human_review_metrics.csv
   improved_evaluation_report.csv
   rag_evaluation_results.csv

Root-level files:
   .gitignore
   requirements.txt

In [25]:
test_code = r'''
import sys
import unittest
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/ShopAssist")

if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

from src.retrieval import (
    load_policies,
    build_retrieval_index,
    search_policies
)


class TestShopAssistRetrieval(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.documents_df = load_policies(
            PROJECT_DIR / "data" / "policies"
        )
        cls.model, cls.index = build_retrieval_index(cls.documents_df)

    def test_all_policy_documents_load(self):
        self.assertEqual(len(self.documents_df), 15)

    def test_policy_sources_are_markdown_files(self):
        self.assertTrue(
            all(source.endswith(".md")
                for source in self.documents_df["source"])
        )

    def test_damaged_item_query(self):
        results = search_policies(
            "My item arrived damaged. What should I do?",
            self.documents_df,
            self.model,
            self.index,
            top_k=3
        )
        self.assertFalse(results.empty)
        self.assertEqual(results.iloc[0]["source"], "damaged_items.md")

    def test_delivery_query(self):
        results = search_policies(
            "How long does standard delivery take?",
            self.documents_df,
            self.model,
            self.index,
            top_k=3
        )
        self.assertFalse(results.empty)
        self.assertEqual(results.iloc[0]["source"], "delivery_policy.md")

    def test_empty_query(self):
        results = search_policies(
            "",
            self.documents_df,
            self.model,
            self.index
        )
        self.assertTrue(results.empty)


if __name__ == "__main__":
    unittest.main(argv=["first-arg-is-ignored"], exit=False)
'''

tests_dir = PROJECT_DIR / "tests"
tests_dir.mkdir(parents=True, exist_ok=True)

test_file = tests_dir / "test_retrieval.py"
test_file.write_text(test_code.strip() + "\n", encoding="utf-8")

print("Created:", test_file)
print("File size:", test_file.stat().st_size, "bytes")

Created: /content/drive/MyDrive/ShopAssist/tests/test_retrieval.py
File size: 1839 bytes

In [26]:
%run /content/drive/MyDrive/ShopAssist/tests/test_retrieval.py

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

.....
----------------------------------------------------------------------
Ran 5 tests in 2.003s

OK

In [27]:
import sys
import unittest
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/ShopAssist")

if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

from src.chatbot import create_chatbot


class TestShopAssistChatbot(unittest.TestCase):

    def test_missing_api_key_raises_error(self):
        with self.assertRaisesRegex(ValueError, "Gemini API key not found"):
            create_chatbot(
                documents_df=None,
                embedding_model=None,
                faiss_index=None,
                api_key=""
            )


suite = unittest.TestLoader().loadTestsFromTestCase(
    TestShopAssistChatbot
)
unittest.TextTestRunner(verbosity=2).run(suite)

test_missing_api_key_raises_error (__main__.TestShopAssistChatbot.test_missing_api_key_raises_error) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.005s

OK

In [28]:
gitignore_content = """# Secrets and environment variables
.env
.env.*
!.env.example
*api_key*
*secret*

# Python cache and compiled files
__pycache__/
*.py[cod]
.pytest_cache/

# Virtual environments
.venv/
venv/
env/

# Notebook checkpoints
.ipynb_checkpoints/

# Model and temporary files
*.pkl
*.joblib
*.pt
*.pth
*.bin
*.safetensors
.cache/
tmp/
temp/
"""

gitignore_file = PROJECT_DIR / ".gitignore"
gitignore_file.write_text(gitignore_content, encoding="utf-8")

print("Created:", gitignore_file)
print(gitignore_file.read_text(encoding="utf-8"))

Created: /content/drive/MyDrive/ShopAssist/.gitignore
# Secrets and environment variables
.env
.env.*
!.env.example
*api_key*
*secret*

# Python cache and compiled files
__pycache__/
*.py[cod]
.pytest_cache/

# Virtual environments
.venv/
venv/
env/

# Notebook checkpoints
.ipynb_checkpoints/

# Model and temporary files
*.pkl
*.joblib
*.pt
*.pth
*.bin
*.safetensors
.cache/
tmp/
temp/

In [29]:
print("ShopAssist root directory:\n")

for item in sorted(PROJECT_DIR.iterdir()):
    suffix = "/" if item.is_dir() else ""
    print(f"  {item.name}{suffix}")

ShopAssist root directory:

  .gitignore
  app/
  data/
  notebooks/
  requirements.txt
  src/
  tests/

In [30]:
from google.colab import userdata
import subprocess
from pathlib import Path
import os

GITHUB_TOKEN = userdata.get("GITHUB_TOKEN")

if not GITHUB_TOKEN:
    raise ValueError(
        "GITHUB_TOKEN was not found in Colab Secrets. "
        "Check the secret name without printing the token."
    )

repo_url = (
    "https://x-access-token:"
    + GITHUB_TOKEN
    + "@github.com/DhruviPatadia/ShopAssist.git"
)

clone_path = Path("/content/ShopAssist")

if (clone_path / ".git").exists():
    print("Git repository already exists:", clone_path)
else:
    result = subprocess.run(
        [
            "git", "clone",
            "https://github.com/DhruviPatadia/ShopAssist.git",
            str(clone_path)
        ],
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        print("Clone failed:")
        print(result.stderr)
    else:
        print("Repository cloned successfully!")

print("\nRepository contents:")
if (clone_path / ".git").exists():
    for item in sorted(clone_path.iterdir()):
        print(" ", item.name)

Repository cloned successfully!

Repository contents:
  .git
  .gitignore
  README.md
  app
  app.py
  app_gemini.py
  data
  notebooks
  requirements-render.txt
  requirements.txt
  src
  tests

In [31]:
from pathlib import Path
import shutil

DRIVE_PROJECT = Path("/content/drive/MyDrive/ShopAssist")
GITHUB_PROJECT = Path("/content/ShopAssist")

# Copy only these new files/folders from Drive.
files_to_copy = [
    ".gitignore",
    "requirements.txt",
    "src",
    "app",
    "tests"
]

for name in files_to_copy:
    source = DRIVE_PROJECT / name
    destination = GITHUB_PROJECT / name

    if not source.exists():
        print(f"Skipped (not found): {name}")
        continue

    if source.is_dir():
        shutil.copytree(source, destination, dirs_exist_ok=True)
    else:
        shutil.copy2(source, destination)

    print(f"Copied: {name}")

print("\nExisting README and notebooks were not copied or overwritten.")

Copied: .gitignore
Copied: requirements.txt
Copied: src
Copied: app
Copied: tests

Existing README and notebooks were not copied or overwritten.

In [32]:
import subprocess

repo_path = "/content/ShopAssist"

result = subprocess.run(
    ["git", "status", "--short"],
    cwd=repo_path,
    capture_output=True,
    text=True
)

print(result.stdout if result.stdout else "No changes detected.")

 M .gitignore
 M app/gradio_app.py

In [33]:
from pathlib import Path

DRIVE_PROJECT = Path("/content/drive/MyDrive/ShopAssist")
GITHUB_PROJECT = Path("/content/ShopAssist")

files_to_check = [
    ".gitignore",
    "requirements.txt",
    "src/retrieval.py",
    "src/chatbot.py",
    "app/gradio_app.py",
    "tests/test_retrieval.py"
]

all_match = True

for name in files_to_check:
    drive_file = DRIVE_PROJECT / name
    github_file = GITHUB_PROJECT / name

    if not drive_file.exists() or not github_file.exists():
        print(f"MISSING: {name}")
        all_match = False
    elif drive_file.read_bytes() == github_file.read_bytes():
        print(f"MATCH:   {name}")
    else:
        print(f"DIFFER:  {name}")
        all_match = False

print("\nAll checked files match:", all_match)

MATCH:   .gitignore
MATCH:   requirements.txt
MATCH:   src/retrieval.py
MATCH:   src/chatbot.py
MATCH:   app/gradio_app.py
MATCH:   tests/test_retrieval.py

All checked files match: True

In [34]:
import subprocess
from google.colab import userdata

repo_path = "/content/ShopAssist"
token = userdata.get("GITHUB_TOKEN")

if not token:
    raise ValueError("GITHUB_TOKEN is missing from Colab Secrets.")

def run_git(args):
    result = subprocess.run(
        ["git"] + args,
        cwd=repo_path,
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr)
    return result.stdout.strip()

# Configure the commit identity for this repository
run_git(["config", "user.name", "ShopAssist Project"])
run_git(["config", "user.email", "shopassist-project@users.noreply.github.com"])

# Stage only the intended additions
run_git([
    "add", "--",
    ".gitignore",
    "requirements.txt",
    "src/",
    "app/",
    "tests/"
])

# Create the commit
run_git([
    "commit", "-m",
    "Add modular ShopAssist chatbot application and tests"
])

print("Commit created successfully.")

# Use the token securely for the push without printing it
remote_url = (
    "https://x-access-token:"
    + token
    + "@github.com/DhruviPatadia/ShopAssist.git"
)

push_result = subprocess.run(
    ["git", "push", remote_url, "HEAD"],
    cwd=repo_path,
    capture_output=True,
    text=True
)

if push_result.returncode == 0:
    print("Push successful!")
else:
    print("Push did not complete:")
    print(push_result.stderr)

Commit created successfully.
Push successful!

In [35]:
%cd /content/ShopAssist

!pip install -q -r requirements.txt

/content/ShopAssist

In [36]:
from pathlib import Path

app_file = Path("/content/ShopAssist/app/gradio_app.py")

assert app_file.exists(), "Gradio application file not found."

print("Application file found.")
print("Ready to launch ShopAssist.")

Application file found.
Ready to launch ShopAssist.

In [37]:
%cd /content/ShopAssist
!python app/gradio_app.py

/content/ShopAssist
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100% 103/103 [00:00<00:00, 15465.50it/s]
Batches: 100% 1/1 [00:00<00:00,  1.43it/s]
Traceback (most recent call last):
  File "/content/ShopAssist/app/gradio_app.py", line 69, in <module>
    app = build_app()
  File "/content/ShopAssist/app/gradio_app.py", line 28, in build_app
    api_key = userdata.get("GEMINI_API_KEY")
  File "/usr/local/lib/python3.13/dist-packages/google/colab/userdata.py", line 62, in get
    resp = _message.blocking_request(
        'GetSecret', request={'key': key}, timeout_sec=10
    )
  File "/usr/local/lib/python3.13/dist-packages/google/colab/_message.py", line 173, in blocking_request
    request_id = send_request(
        request_type, request, parent=parent, expect_reply=True
    )
  File "/usr/local/lib/python3.13/dist-packages/google/colab/_message.py", line 117, in send_request
    instance = ipython.get_kernelapp()
  File "/usr/local/lib/python3.13/dist-packages/google/colab/_ipython.py", line 28, in get_kernelapp
    return get_ipython().kernel.parent
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'kernel'

In [38]:
from pathlib import Path

app_file = Path("/content/ShopAssist/app/gradio_app.py")
app_code = app_file.read_text(encoding="utf-8")

app_code = app_code.replace(
    "from google.colab import userdata\n",
    "import os\n"
)

app_code = app_code.replace(
    '    api_key = userdata.get("GEMINI_API_KEY")',
    '    api_key = os.environ.get("GEMINI_API_KEY")'
)

app_file.write_text(app_code, encoding="utf-8")

print("Updated app/gradio_app.py")
print("Colab userdata dependency removed:", "from google.colab import userdata" not in app_code)
print("Environment variable lookup added:", 'os.environ.get("GEMINI_API_KEY")' in app_code)

Updated app/gradio_app.py
Colab userdata dependency removed: True
Environment variable lookup added: True

In [39]:
from google.colab import userdata
import os
import subprocess

# Retrieve the secret in the notebook's supported environment
gemini_key = userdata.get("GEMINI_API_KEY")

if not gemini_key:
    raise ValueError("GEMINI_API_KEY is missing from Colab Secrets.")

# Pass it to the child process without printing it
app_env = os.environ.copy()
app_env["GEMINI_API_KEY"] = gemini_key

process = subprocess.Popen(
    ["python", "/content/ShopAssist/app/gradio_app.py"],
    cwd="/content/ShopAssist",
    env=app_env
)

print("ShopAssist application process started.")
print("Process ID:", process.pid)

ShopAssist application process started.
Process ID: 2047

In [40]:
import time

time.sleep(3)

print("Process running:", process.poll() is None)

if process.poll() is None:
    print("ShopAssist is still running.")
    print("Check the next cell for the Gradio URL.")
else:
    print("Process exited with code:", process.returncode)
    print("Check the error output from the process.")

Process running: True
ShopAssist is still running.
Check the next cell for the Gradio URL.

In [41]:
process.terminate()
process.wait(timeout=10)

print("Background process stopped.")

Background process stopped.

In [42]:
from pathlib import Path

app_file = Path("/content/ShopAssist/app/gradio_app.py")
app_code = app_file.read_text(encoding="utf-8")

for line_number, line in enumerate(app_code.splitlines(), start=1):
    if "api_key" in line.lower() or "userdata" in line.lower():
        print(f"{line_number}: {line}")

28:     api_key = os.environ.get("GEMINI_API_KEY")
34:         api_key=api_key

In [43]:
import os
import subprocess
from google.colab import userdata

key = userdata.get("GEMINI_API_KEY")
env = os.environ.copy()
env["GEMINI_API_KEY"] = key

check = subprocess.run(
    [
        "python", "-c",
        "import os; print('Child process sees key:', bool(os.environ.get('GEMINI_API_KEY')))"
    ],
    env=env,
    capture_output=True,
    text=True
)

print(check.stdout)
print(check.stderr if check.returncode != 0 else "")

Child process sees key: True

In [44]:
from pathlib import Path

app_file = Path("/content/ShopAssist/app/gradio_app.py")
app_code = app_file.read_text(encoding="utf-8")

old_line = '    api_key = os.environ.get("GEMINI_API_KEY")'
new_line = '    api_key = os.environ.get("GEMINI_API_KEY", "").strip()'

if old_line in app_code:
    app_code = app_code.replace(old_line, new_line)
    app_file.write_text(app_code, encoding="utf-8")
    print("Updated API key lookup.")
elif new_line in app_code:
    print("API key lookup already updated.")
else:
    print("Expected API key line not found. Inspect the file before changing it.")

Updated API key lookup.

In [45]:
app_code = app_file.read_text(encoding="utf-8")

for number, line in enumerate(app_code.splitlines(), start=1):
    if "api_key" in line.lower():
        print(f"{number}: {line}")

28:     api_key = os.environ.get("GEMINI_API_KEY", "").strip()
34:         api_key=api_key

In [46]:
import gradio
print("Gradio version:", gradio.__version__)

Gradio version: 6.30.0

In [47]:
from pathlib import Path

app_file = Path("/content/ShopAssist/app/gradio_app.py")
lines = app_file.read_text(encoding="utf-8").splitlines()

for number, line in enumerate(lines, start=1):
    if "launch(" in line or "api_key =" in line or "build_app()" in line:
        print(f"{number}: {line}")

20: def build_app():
28:     api_key = os.environ.get("GEMINI_API_KEY", "").strip()
69:     app = build_app()
70:     app.launch(share=True)

In [48]:
import gradio as gr

demo = gr.Interface(
    fn=lambda text: f"ShopAssist test received: {text}",
    inputs=gr.Textbox(label="Test message"),
    outputs=gr.Textbox(label="Response"),
    title="ShopAssist Startup Test"
)

demo.launch(share=True, debug=False)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://6482ec969987571f6c.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [49]:
import os
import subprocess
from google.colab import userdata

key = userdata.get("GEMINI_API_KEY")
env = os.environ.copy()
env["GEMINI_API_KEY"] = key

result = subprocess.run(
    [
        "python", "-c",
        "import os; print('Gemini key available to app:', bool(os.environ.get('GEMINI_API_KEY')))"
    ],
    env=env,
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

Gemini key available to app: True

In [50]:
import os
import subprocess
from google.colab import userdata

gemini_key = userdata.get("GEMINI_API_KEY")

if not gemini_key:
    raise ValueError("GEMINI_API_KEY is unavailable.")

app_env = os.environ.copy()
app_env["GEMINI_API_KEY"] = gemini_key

print("Starting ShopAssist...")

result = subprocess.run(
    ["python", "-u", "app/gradio_app.py"],
    cwd="/content/ShopAssist",
    env=app_env,
    text=True,
    capture_output=True,
    timeout=120
)

print("Return code:", result.returncode)
print("\n--- Application output ---")
print(result.stdout)
print("\n--- Errors, if any ---")
print(result.stderr)

Starting ShopAssist...

KeyboardInterrupt:

In [51]:
import os
import subprocess
import time
from pathlib import Path
from google.colab import userdata

gemini_key = userdata.get("GEMINI_API_KEY")
if not gemini_key:
    raise ValueError("GEMINI_API_KEY is unavailable.")

app_env = os.environ.copy()
app_env["GEMINI_API_KEY"] = gemini_key

log_file = Path("/content/shopassist_app.log")
log_handle = open(log_file, "w")

app_process = subprocess.Popen(
    ["python", "-u", "app/gradio_app.py"],
    cwd="/content/ShopAssist",
    env=app_env,
    stdout=log_handle,
    stderr=subprocess.STDOUT
)

print("Started process:", app_process.pid)
time.sleep(15)

print("\n--- Startup log ---")
print(log_file.read_text(encoding="utf-8", errors="replace"))

print("\nProcess running:", app_process.poll() is None)

Started process: 2503

--- Startup log ---
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.


Process running: True

In [52]:
import time
from pathlib import Path

time.sleep(15)

log_file = Path("/content/shopassist_app.log")

print("Process running:", app_process.poll() is None)
print("Log size:", log_file.stat().st_size, "bytes")
print("\n--- Latest log output ---")
print(log_file.read_text(encoding="utf-8", errors="replace"))

Process running: True
Log size: 843 bytes

--- Latest log output ---
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5882.77it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  1.95it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00,  1.95it/s]
* Running on local URL:  http://127.0.0.1:7861
* Running on public URL: https://1a45e7d289b0609882.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [53]:
from pathlib import Path
import subprocess

repo_path = Path("/content/ShopAssist")

print("Current Git status:")
result = subprocess.run(
    ["git", "status", "--short"],
    cwd=repo_path,
    capture_output=True,
    text=True
)
print(result.stdout or "No changes detected.")

Current Git status:
 M app/gradio_app.py
?? .gradio/

In [54]:
from pathlib import Path

repo_path = Path("/content/ShopAssist")
gradio_dir = repo_path / ".gradio"

if gradio_dir.exists():
    print("Files in .gradio/:")
    for item in sorted(gradio_dir.rglob("*")):
        if item.is_file():
            print(item.relative_to(repo_path))
else:
    print(".gradio/ does not exist.")

Files in .gradio/:
.gradio/certificate.pem

In [55]:
from pathlib import Path

repo_path = Path("/content/ShopAssist")
gitignore_file = repo_path / ".gitignore"

existing = gitignore_file.read_text(encoding="utf-8") if gitignore_file.exists() else ""

addition = "\n# Local Gradio configuration\n.gradio/\n"

if ".gradio/" not in existing:
    gitignore_file.write_text(existing.rstrip() + "\n" + addition, encoding="utf-8")

print("Updated .gitignore to ignore .gradio/")

Updated .gitignore to ignore .gradio/

In [56]:
import subprocess

result = subprocess.run(
    ["git", "status", "--short"],
    cwd="/content/ShopAssist",
    capture_output=True,
    text=True
)

print(result.stdout or "No changes detected.")

 M .gitignore
 M app/gradio_app.py

In [57]:
import subprocess
from google.colab import userdata

repo_path = "/content/ShopAssist"
token = userdata.get("GITHUB_TOKEN")

if not token:
    raise ValueError("GITHUB_TOKEN is missing from Colab Secrets.")

def run_git(args):
    result = subprocess.run(
        ["git"] + args,
        cwd=repo_path,
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr)
    return result.stdout.strip()

# Stage only the two intended files
run_git(["add", "--", ".gitignore", "app/gradio_app.py"])

# Commit
run_git([
    "commit", "-m",
    "Fix app configuration and ignore local Gradio files"
])

print("Commit created successfully.")

# Push without displaying the token
remote_url = (
    "https://x-access-token:"
    + token
    + "@github.com/DhruviPatadia/ShopAssist.git"
)

result = subprocess.run(
    ["git", "push", remote_url, "HEAD"],
    cwd=repo_path,
    capture_output=True,
    text=True
)

if result.returncode == 0:
    print("Push successful!")
else:
    print("Push failed:")
    print(result.stderr)

Commit created successfully.
Push successful!

In [58]:
from pathlib import Path

readme_path = Path("/content/ShopAssist/README.md")

print("README exists:", readme_path.exists())

if readme_path.exists():
    print("\n--- Current README ---\n")
    print(readme_path.read_text(encoding="utf-8"))

README exists: True

--- Current README ---

---
title: ShopAssist AI
emoji: 🛍️
colorFrom: blue
colorTo: indigo
sdk: gradio
sdk_version: 5.49.1
app_file: app.py
pinned: false
---

# ShopAssist AI — Intelligent E-commerce Customer Support Agent

ShopAssist AI is a retrieval-augmented customer support chatbot designed to answer common e-commerce questions using a collection of policy documents. It combines semantic search, vector retrieval, a large language model, and a Gradio chat interface to provide answers grounded in relevant policies.

## Project Overview

E-commerce customers often need quick, consistent answers about delivery, returns, refunds, replacements, payments, and other order-related questions.

ShopAssist retrieves relevant policy documents and uses them as context for generating responses. It is designed to cite its policy sources and acknowledge when the available documentation does not specify an answer.

## Key Features

- **Semantic search:** Uses Sentence Transformers to encode policy documents and customer queries.
- **Vector retrieval:** Uses FAISS to retrieve relevant policies by similarity.
- **Retrieval-Augmented Generation (RAG):** Supplies retrieved policy content to Gemini when generating answers.
- **Source-grounded responses:** Encourages answers to cite the relevant policy filenames.
- **Conversation context:** Passes recent chat history to the answer-generation function.
- **Interactive interface:** Provides a chat interface built with Gradio.
- **Retrieval tests:** Includes automated tests for policy loading, relevant-document retrieval, empty queries, and chatbot configuration.

## Architecture

```text
Customer question
       |
       v
Sentence Transformer
       |
       v
FAISS similarity search
       |
       v
Top relevant policy documents
       |
       v
Policy context + recent conversation
       |
       v
Gemini answer generation
       |
       v
Response with policy source citations
       |
       v
Gradio chat interface
```

### Technology Stack

| Component | Technology |
|---|---|
| Programming language | Python |
| Embedding model | `sentence-transformers/all-MiniLM-L6-v2` |
| Vector search | FAISS |
| Data processing | pandas, NumPy |
| Language model | Gemini via `google-genai` |
| Chat interface | Gradio |
| Development environment | Google Colab |
| Version control | Git and GitHub |

## Repository Structure

```text
ShopAssist/
├── app/
│   └── gradio_app.py
├── data/
│   ├── policies/
│   └── evaluation/
├── notebooks/
│   ├── 01_data_exploration.ipynb
│   └── 02_chatbot_app.ipynb
├── src/
│   ├── retrieval.py
│   └── chatbot.py
├── tests/
│   └── test_retrieval.py
├── .gitignore
├── requirements.txt
└── README.md
```

## Knowledge Base

The knowledge base contains 15 Markdown policy documents covering:

- Account policies
- Cancellations
- Damaged and missing items
- Delivery and shipping
- Discounts and gift cards
- International shipping
- Payment methods and privacy
- Refunds, replacements, and returns
- Warranty information

The policies are stored in `data/policies/`.

## Retrieval Evaluation

The initial retrieval evaluation used a set of customer questions with expected relevant policy documents.

| Metric | Recorded result |
|---|---:|
| Mean Reciprocal Rank (MRR) | 0.9474 |
| Recall@3 | 100% |

These figures describe the earlier retrieval evaluation recorded during development. They are retrieval metrics, not measurements of overall answer correctness or customer satisfaction.

The project also includes `data/evaluation/rag_evaluation_results.csv` for reviewing previously recorded answer-generation evaluation results.

## Human-Reviewed Answer Evaluation

ShopAssist AI was evaluated using a benchmark of 20 customer questions covering returns, delivery, cancellations, international shipping, replacements, refunds, payments, discounts, missing items, warranties, gift cards, privacy, and an out-of-scope address-change question.

The benchmark compares generated responses with expected answers and relevant policy documents. Responses were reviewed using three criteria: answer correctness, policy-source support, and citation correctness.

### Preliminary Results

| Metric | Result |
|---|---:|
| Questions reviewed | 20 |
| Answers labelled correct | 20/20 (100%) |
| Answers marked as source-supported | 19/20 (95%) |
| Answers with uncertain source support | 1/20 (5%) |
| Citation accuracy among applicable labels | 19/19 (100%) |

**Interpretation:** These are preliminary, human-reviewed results based on the current benchmark labels. They should not be interpreted as independently validated model accuracy or as evidence of performance across all possible customer queries.

One question asked whether a delivery address could be changed after dispatch. The available policies did not specify whether this was possible, and the chatbot acknowledged the information gap rather than asserting an unsupported policy.

Citation accuracy excludes that question because its citation label was marked `not_applicable`. The international-shipping source was also reviewed against the policy documents, which confirm shipping to selected countries.

### Evaluation Files

The evaluation artifacts are stored in `data/evaluation/`:

- `evaluation_questions.csv` — benchmark questions, expected answers, and expected sources.
- `rag_evaluation_results.csv` — recorded retrieval and generated-answer results.
- `improved_evaluation_report.csv` — additional retrieval and phrase-check indicators.
- `human_review_benchmark.csv` — human-review labels and notes.
- `human_review_metrics.csv` — summary of the preliminary human-review metrics.

The benchmark is small and reflects a limited set of policy questions. Further evaluation should include more paraphrases, ambiguous queries, unsupported questions, and independent review of answer claims and citations.

## Automated Tests

The retrieval test suite is located at `tests/test_retrieval.py`.

The five recorded retrieval tests passed during development. They check:

1. Loading all 15 policy documents.
2. Confirming policy sources use Markdown filenames.
3. Retrieving the damaged-item policy for a damaged-item query.
4. Retrieving the delivery policy for a standard-delivery query.
5. Returning no results for an empty query.

A separate configuration check also passed for handling a missing Gemini API key.

Run the retrieval tests from the project root:

```bash
python tests/test_retrieval.py
```

The first run may download the embedding model if it is not cached.

## Setup and Usage

### 1. Install dependencies

Use Python in an environment compatible with the packages listed in `requirements.txt`.

```bash
pip install -r requirements.txt
```

### 2. Configure the Gemini API key

Set the `GEMINI_API_KEY` environment variable securely. Never commit API keys or other credentials to GitHub.

For example, in a terminal:

```bash
export GEMINI_API_KEY="your-api-key"
```

Use the equivalent environment-variable configuration for your operating system or deployment environment.

### 3. Launch the application

From the repository root:

```bash
python app/gradio_app.py
```

The application loads the policy documents, builds the retrieval index, and launches the Gradio interface. A public share URL may be generated by Gradio; such links are temporary and are not a permanent deployment.

### Example Questions

- How long does standard delivery take?
- How can I return an item?
- My item arrived damaged. What should I do?
- Can I change my delivery address after dispatch?

## Limitations

- Responses depend on the completeness and accuracy of the available policy documents.
- Semantic retrieval can return relevant but not always optimal documents.
- Source citations are generated as part of the model response and are not independently verified against every claim.
- Answer quality has not been established through a comprehensive, independently validated evaluation.
- Gemini API availability and rate limits may affect response generation.
- The current Gradio share link is intended for temporary testing, not permanent production hosting.

## Future Improvements

- Expand and strengthen automated evaluation of retrieval and answer correctness.
- Improve handling of follow-up questions and ambiguous customer requests.
- Validate citations and claims against retrieved policy text.
- Add more robust error handling, logging, and monitoring.
- Deploy the application to a persistent hosting environment.
- Add broader unit and integration tests.

## Project Status

The modular retrieval and chatbot code has been created, the Gradio application has launched successfully in Google Colab, and initial retrieval and manual chatbot checks have been completed.

---

Developed as an AI customer-support portfolio project.

In [59]:
from pathlib import Path

repo_path = Path("/content/ShopAssist")
readme_path = repo_path / "README.md"

readme_content = r"""
# ShopAssist AI — Intelligent E-commerce Customer Support Agent

ShopAssist AI is a retrieval-augmented customer support chatbot designed to answer common e-commerce questions using a collection of policy documents. It combines semantic search, vector retrieval, a large language model, and a Gradio chat interface to provide answers grounded in relevant policies.

## Project Overview

E-commerce customers often need quick, consistent answers about delivery, returns, refunds, replacements, payments, and other order-related questions.

ShopAssist retrieves relevant policy documents and uses them as context for generating responses. It is designed to cite its policy sources and acknowledge when the available documentation does not specify an answer.

## Key Features

- **Semantic search:** Uses Sentence Transformers to encode policy documents and customer queries.
- **Vector retrieval:** Uses FAISS to retrieve relevant policies by similarity.
- **Retrieval-Augmented Generation (RAG):** Supplies retrieved policy content to Gemini when generating answers.
- **Source-grounded responses:** Encourages answers to cite the relevant policy filenames.
- **Conversation context:** Passes recent chat history to the answer-generation function.
- **Interactive interface:** Provides a chat interface built with Gradio.
- **Retrieval tests:** Includes automated tests for policy loading, relevant-document retrieval, empty queries, and chatbot configuration.

## Architecture

```text
Customer question
       |
       v
Sentence Transformer
       |
       v
FAISS similarity search
       |
       v
Top relevant policy documents
       |
       v
Policy context + recent conversation
       |
       v
Gemini answer generation
       |
       v
Response with policy source citations
       |
       v
Gradio chat interface
```

### Technology Stack

| Component | Technology |
|---|---|
| Programming language | Python |
| Embedding model | `sentence-transformers/all-MiniLM-L6-v2` |
| Vector search | FAISS |
| Data processing | pandas, NumPy |
| Language model | Gemini via `google-genai` |
| Chat interface | Gradio |
| Development environment | Google Colab |
| Version control | Git and GitHub |

## Repository Structure

```text
ShopAssist/
├── app/
│   └── gradio_app.py
├── data/
│   ├── policies/
│   └── evaluation/
├── notebooks/
│   ├── 01_data_exploration.ipynb
│   └── 02_chatbot_app.ipynb
├── src/
│   ├── retrieval.py
│   └── chatbot.py
├── tests/
│   └── test_retrieval.py
├── .gitignore
├── requirements.txt
└── README.md
```

## Knowledge Base

The knowledge base contains 15 Markdown policy documents covering:

- Account policies
- Cancellations
- Damaged and missing items
- Delivery and shipping
- Discounts and gift cards
- International shipping
- Payment methods and privacy
- Refunds, replacements, and returns
- Warranty information

The policies are stored in `data/policies/`.

## Retrieval Evaluation

The initial retrieval evaluation used a set of customer questions with expected relevant policy documents.

| Metric | Recorded result |
|---|---:|
| Mean Reciprocal Rank (MRR) | 0.9474 |
| Recall@3 | 100% |

These figures describe the earlier retrieval evaluation recorded during development. They are retrieval metrics, not measurements of overall answer correctness or customer satisfaction.

The project also includes `data/evaluation/rag_evaluation_results.csv` for reviewing previously recorded answer-generation evaluation results.

## Automated Tests

The retrieval test suite is located at `tests/test_retrieval.py`.

The five recorded retrieval tests passed during development. They check:

1. Loading all 15 policy documents.
2. Confirming policy sources use Markdown filenames.
3. Retrieving the damaged-item policy for a damaged-item query.
4. Retrieving the delivery policy for a standard-delivery query.
5. Returning no results for an empty query.

A separate configuration check also passed for handling a missing Gemini API key.

Run the retrieval tests from the project root:

```bash
python tests/test_retrieval.py
```

The first run may download the embedding model if it is not cached.

## Setup and Usage

### 1. Install dependencies

Use Python in an environment compatible with the packages listed in `requirements.txt`.

```bash
pip install -r requirements.txt
```

### 2. Configure the Gemini API key

Set the `GEMINI_API_KEY` environment variable securely. Never commit API keys or other credentials to GitHub.

For example, in a terminal:

```bash
export GEMINI_API_KEY="your-api-key"
```

Use the equivalent environment-variable configuration for your operating system or deployment environment.

### 3. Launch the application

From the repository root:

```bash
python app/gradio_app.py
```

The application loads the policy documents, builds the retrieval index, and launches the Gradio interface. A public share URL may be generated by Gradio; such links are temporary and are not a permanent deployment.

### Example Questions

- How long does standard delivery take?
- How can I return an item?
- My item arrived damaged. What should I do?
- Can I change my delivery address after dispatch?

## Limitations

- Responses depend on the completeness and accuracy of the available policy documents.
- Semantic retrieval can return relevant but not always optimal documents.
- Source citations are generated as part of the model response and are not independently verified against every claim.
- Answer quality has not been established through a comprehensive, independently validated evaluation.
- Gemini API availability and rate limits may affect response generation.
- The current Gradio share link is intended for temporary testing, not permanent production hosting.

## Future Improvements

- Expand and strengthen automated evaluation of retrieval and answer correctness.
- Improve handling of follow-up questions and ambiguous customer requests.
- Validate citations and claims against retrieved policy text.
- Add more robust error handling, logging, and monitoring.
- Deploy the application to a persistent hosting environment.
- Add broader unit and integration tests.

## Project Status

The modular retrieval and chatbot code has been created, the Gradio application has launched successfully in Google Colab, and initial retrieval and manual chatbot checks have been completed.

---

Developed as an AI customer-support portfolio project.
"""

readme_path.write_text(readme_content.strip() + "\n", encoding="utf-8")

print("README updated:", readme_path)
print("Characters:", len(readme_content))
print("\nPreview:\n")
print("\n".join(readme_path.read_text(encoding="utf-8").splitlines()[:25]))

README updated: /content/ShopAssist/README.md
Characters: 6420

Preview:

# ShopAssist AI — Intelligent E-commerce Customer Support Agent

ShopAssist AI is a retrieval-augmented customer support chatbot designed to answer common e-commerce questions using a collection of policy documents. It combines semantic search, vector retrieval, a large language model, and a Gradio chat interface to provide answers grounded in relevant policies.

## Project Overview

E-commerce customers often need quick, consistent answers about delivery, returns, refunds, replacements, payments, and other order-related questions.

ShopAssist retrieves relevant policy documents and uses them as context for generating responses. It is designed to cite its policy sources and acknowledge when the available documentation does not specify an answer.

## Key Features

- **Semantic search:** Uses Sentence Transformers to encode policy documents and customer queries.
- **Vector retrieval:** Uses FAISS to retrieve relevant policies by similarity.
- **Retrieval-Augmented Generation (RAG):** Supplies retrieved policy content to Gemini when generating answers.
- **Source-grounded responses:** Encourages answers to cite the relevant policy filenames.
- **Conversation context:** Passes recent chat history to the answer-generation function.
- **Interactive interface:** Provides a chat interface built with Gradio.
- **Retrieval tests:** Includes automated tests for policy loading, relevant-document retrieval, empty queries, and chatbot configuration.

## Architecture

```text
Customer question
       |

In [60]:
import subprocess

result = subprocess.run(
    ["git", "diff", "--check"],
    cwd="/content/ShopAssist",
    capture_output=True,
    text=True
)
print(result.stdout or "No whitespace errors.")
print(result.stderr)

result = subprocess.run(
    ["git", "status", "--short"],
    cwd="/content/ShopAssist",
    capture_output=True,
    text=True
)
print("\nGit status:\n", result.stdout)

No whitespace errors.


Git status:
  M README.md

In [61]:
import subprocess
from google.colab import userdata

repo_path = "/content/ShopAssist"
token = userdata.get("GITHUB_TOKEN")

if not token:
    raise ValueError("GITHUB_TOKEN is missing from Colab Secrets.")

def run_git(args):
    result = subprocess.run(
        ["git"] + args,
        cwd=repo_path,
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr)
    return result.stdout.strip()

# Stage and commit only the README
run_git(["add", "--", "README.md"])
run_git(["commit", "-m", "Improve project documentation"])

print("README commit created successfully.")

# Push without displaying the token
remote_url = (
    "https://x-access-token:"
    + token
    + "@github.com/DhruviPatadia/ShopAssist.git"
)

result = subprocess.run(
    ["git", "push", remote_url, "HEAD"],
    cwd=repo_path,
    capture_output=True,
    text=True
)

if result.returncode == 0:
    print("README pushed successfully!")
else:
    print("Push failed:")
    print(result.stderr)

README commit created successfully.
README pushed successfully!

In [62]:
from pathlib import Path
import pandas as pd

PROJECT_DIR = Path("/content/drive/MyDrive/ShopAssist")
EVALUATION_DIR = PROJECT_DIR / "data" / "evaluation"

for filename in [
    "evaluation_questions.csv",
    "rag_evaluation_results.csv"
]:
    path = EVALUATION_DIR / filename

    print(f"\n{'=' * 60}")
    print(filename)

    if path.exists():
        df = pd.read_csv(path)
        print("Shape:", df.shape)
        print("Columns:", df.columns.tolist())
        display(df.head(5))
    else:
        print("File not found:", path)

============================================================
evaluation_questions.csv
Shape: (20, 5)
Columns: ['id', 'question', 'expected_source', 'expected_answer', 'query_type']

,id,question,expected_source,expected_answer,query_type
0,1,How long do I have to return an item?,returns_policy.md,30 days,direct
1,2,What's the deadline for sending something back?,returns_policy.md,30 days,paraphrased
2,3,Can I return a damaged product?,damaged_items.md,Yes,direct
3,4,My item arrived damaged. What should I do?,damaged_items.md,Contact support and provide photographs if req...,customer_scenario
4,5,How long does standard delivery take?,delivery_policy.md,3–5 working days after dispatch,direct

============================================================
rag_evaluation_results.csv
Shape: (20, 5)
Columns: ['question', 'expected_source', 'expected_answer', 'generated_answer', 'retrieved_source']

,question,expected_source,expected_answer,generated_answer,retrieved_source
0,How long do I have to return an item?,returns_policy.md,30 days,You have 30 days from delivery to return an el...,returns_policy.md
1,What's the deadline for sending something back?,returns_policy.md,30 days,You may return eligible products within 30 day...,returns_policy.md
2,Can I return a damaged product?,damaged_items.md,Yes,Items that are damaged when received are handl...,damaged_items.md
3,My item arrived damaged. What should I do?,damaged_items.md,Contact support and provide photographs if req...,"If your item arrived damaged, you should conta...",damaged_items.md
4,How long does standard delivery take?,delivery_policy.md,3–5 working days after dispatch,Standard domestic delivery takes 3–5 working d...,delivery_policy.md

In [63]:
from pathlib import Path
import pandas as pd
import re

PROJECT_DIR = Path("/content/drive/MyDrive/ShopAssist")
EVALUATION_DIR = PROJECT_DIR / "data" / "evaluation"

questions_df = pd.read_csv(EVALUATION_DIR / "evaluation_questions.csv")
results_df = pd.read_csv(EVALUATION_DIR / "rag_evaluation_results.csv")

# 1. Source retrieval accuracy
results_df["source_correct"] = (
    results_df["expected_source"].str.strip()
    == results_df["retrieved_source"].str.strip()
)

source_accuracy = results_df["source_correct"].mean()

print(f"Source retrieval accuracy: {source_accuracy:.2%}")
print(
    f"Correct source: {results_df['source_correct'].sum()}"
    f"/{len(results_df)}"
)

# 2. Lightweight expected-answer keyword/phrase check
def answer_check(expected, generated):
    if pd.isna(expected) or pd.isna(generated):
        return False

    expected_text = str(expected).strip().lower()
    generated_text = str(generated).strip().lower()

    if not expected_text:
        return False

    # Direct phrase match
    if expected_text in generated_text:
        return True

    # For short expected answers, avoid unreliable substring checks
    # such as matching "yes" inside another word.
    expected_words = re.findall(r"\b[\w–-]+\b", expected_text)
    generated_words = set(re.findall(r"\b[\w–-]+\b", generated_text))

    if len(expected_words) <= 2:
        return all(word in generated_words for word in expected_words)

    return False

results_df["answer_keyword_check"] = results_df.apply(
    lambda row: answer_check(
        row["expected_answer"],
        row["generated_answer"]
    ),
    axis=1
)

keyword_rate = results_df["answer_keyword_check"].mean()

print(f"\nExpected-answer keyword/phrase check rate: {keyword_rate:.2%}")
print(
    f"Passed checks: {results_df['answer_keyword_check'].sum()}"
    f"/{len(results_df)}"
)

# 3. Query-type breakdown
if "query_type" in questions_df.columns:
    type_df = questions_df[["question", "query_type"]].merge(
        results_df[["question", "source_correct", "answer_keyword_check"]],
        on="question",
        how="left"
    )

    type_summary = type_df.groupby("query_type", dropna=False).agg(
        questions=("question", "count"),
        source_accuracy=("source_correct", "mean"),
        keyword_check_rate=("answer_keyword_check", "mean")
    ).reset_index()

    display(type_summary)

# 4. Inspect rows needing review
print("\nRows where the expected source was not retrieved:")
display(
    results_df.loc[
        ~results_df["source_correct"],
        ["question", "expected_source", "retrieved_source"]
    ]
)

print("\nRows failing the answer keyword/phrase check:")
display(
    results_df.loc[
        ~results_df["answer_keyword_check"],
        ["question", "expected_answer", "generated_answer"]
    ]
)

Source retrieval accuracy: 85.00%
Correct source: 17/20

Expected-answer keyword/phrase check rate: 40.00%
Passed checks: 8/20

          query_type  questions  source_accuracy  keyword_check_rate
0  customer_scenario          3         1.000000                 0.0
1             direct         12         0.916667                 0.5
2       out_of_scope          1         0.000000                 0.0
3        paraphrased          4         0.750000                 0.5

Rows where the expected source was not retrieved:

,question,expected_source,retrieved_source
8,Do you ship internationally?,shipping_policy.md,international_shipping.md
9,Can you deliver orders outside the country?,shipping_policy.md,international_shipping.md
19,Can I change my delivery address after the ord...,NaN,delivery_policy.md

Rows failing the answer keyword/phrase check:

,question,expected_answer,generated_answer
2,Can I return a damaged product?,Yes,Items that are damaged when received are handl...
3,My item arrived damaged. What should I do?,Contact support and provide photographs if req...,"If your item arrived damaged, you should conta..."
4,How long does standard delivery take?,3–5 working days after dispatch,Standard domestic delivery takes 3–5 working d...
5,When should I expect my standard delivery?,3–5 working days after dispatch,Standard domestic delivery takes 3–5 working d...
8,Do you ship internationally?,"Yes, to selected countries","Yes, we offer international shipping to select..."
9,Can you deliver orders outside the country?,"Yes, to selected countries","Yes, we offer international shipping to select..."
11,I received the wrong product. Can you send me ...,"Yes, a replacement may be requested","Yes, you may request a replacement if you rece..."
13,What payment methods do you accept?,Major debit and credit cards and other methods...,"Hello! We accept major debit and credit cards,..."
14,Can I use more than one discount code?,Normally only one promotional discount code,Only one promotional discount code can normall...
15,What happens if something is missing from my d...,Contact support and the issue will be investig...,If an expected item is missing from your deliv...
18,What information should I avoid sharing with c...,Passwords and full payment card numbers,"You should avoid sharing passwords, full payme..."
19,Can I change my delivery address after the ord...,NaN,"I am sorry, but the provided policies do not c..."

In [ ]:
from pathlib import Path
import pandas as pd
import re

PROJECT_DIR = Path("/content/drive/MyDrive/ShopAssist")
EVALUATION_DIR = PROJECT_DIR / "data" / "evaluation"

results_df = pd.read_csv(
    EVALUATION_DIR / "rag_evaluation_results.csv"
)

# Explicitly identify a known alternative source for international shipping.
# This mapping should be reviewed against the actual policy contents.
alternative_sources = {
    "shipping_policy.md": {"international_shipping.md"}
}

def exact_source_match(row):
    expected = row["expected_source"]
    retrieved = row["retrieved_source"]

    if pd.isna(expected) or pd.isna(retrieved):
        return None

    return str(expected).strip() == str(retrieved).strip()

def source_relevant(row):
    expected = row["expected_source"]
    retrieved = row["retrieved_source"]

    if pd.isna(expected) or pd.isna(retrieved):
        return None

    expected = str(expected).strip()
    retrieved = str(retrieved).strip()

    return (
        expected == retrieved
        or retrieved in alternative_sources.get(expected, set())
    )

def normalize_text(text):
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = text.replace("–", "-").replace("—", "-")
    return re.sub(r"\s+", " ", text).strip()

results_df["exact_source_match"] = results_df.apply(
    exact_source_match, axis=1
)
results_df["source_relevant_under_mapping"] = results_df.apply(
    source_relevant, axis=1
)

# A conservative lexical diagnostic, not a semantic correctness metric.
results_df["expected_phrase_present"] = results_df.apply(
    lambda row: (
        normalize_text(row["expected_answer"]) in
        normalize_text(row["generated_answer"])
        if normalize_text(row["expected_answer"])
        else False
    ),
    axis=1
)

results_df["needs_manual_review"] = (
    results_df["source_relevant_under_mapping"].ne(True)
    | ~results_df["expected_phrase_present"]
)

output_path = EVALUATION_DIR / "improved_evaluation_report.csv"
results_df.to_csv(output_path, index=False)

print("Saved:", output_path)
print("\nExact source match:")
print(
    f"{results_df['exact_source_match'].eq(True).sum()} / "
    f"{results_df['exact_source_match'].notna().sum()}"
)

valid_relevance = results_df["source_relevant_under_mapping"].dropna()
print("\nSource relevance under the explicit mapping:")
print(f"{valid_relevance.sum()} / {len(valid_relevance)}")

print("\nExpected phrase present:")
print(
    f"{results_df['expected_phrase_present'].sum()} / "
    f"{len(results_df)}"
)

print("\nRows requiring manual review:")
display(
    results_df.loc[
        results_df["needs_manual_review"],
        [
            "question",
            "expected_source",
            "retrieved_source",
            "expected_answer",
            "generated_answer"
        ]
    ]
)

In [ ]:
from pathlib import Path
import pandas as pd

PROJECT_DIR = Path("/content/drive/MyDrive/ShopAssist")
EVALUATION_DIR = PROJECT_DIR / "data" / "evaluation"

results_df = pd.read_csv(
    EVALUATION_DIR / "rag_evaluation_results.csv"
)

review_df = results_df[
    [
        "question",
        "expected_source",
        "expected_answer",
        "generated_answer",
        "retrieved_source"
    ]
].copy()

review_df["human_verdict"] = ""
review_df["source_supported"] = ""
review_df["citation_correct"] = ""
review_df["review_notes"] = ""

review_path = EVALUATION_DIR / "human_review_benchmark.csv"
review_df.to_csv(review_path, index=False)

print("Created:", review_path)
print("Rows to review:", len(review_df))
print("\nFirst five rows:")
display(review_df.head())

In [ ]:
from pathlib import Path
import pandas as pd
from IPython.display import display

file_path = Path(
    "/content/drive/MyDrive/ShopAssist/data/evaluation/human_review_benchmark.csv"
)

df = pd.read_csv(file_path)

print("File:", file_path.name)
print("Columns:", df.columns.tolist())
print("Shape:", df.shape)

display(df.head())

In [ ]:
import pandas as pd
from pathlib import Path

path = Path(
    "/content/drive/MyDrive/ShopAssist/data/evaluation/"
    "human_review_benchmark.csv"
)

df = pd.read_csv(path)

reviews = [
    ("correct", "yes", "yes", "Correct return deadline; verify against returns policy."),
    ("correct", "yes", "yes", "Correct deadline; additional replacement detail."),
    ("correct", "yes", "yes", "Damaged-item guidance and possible remedies."),
    ("correct", "yes", "yes", "Contact support and photo guidance."),
    ("correct", "yes", "yes", "Correct delivery estimate after dispatch."),
    ("correct", "yes", "yes", "Correct estimate; processing time is distinguished."),
    ("correct", "yes", "yes", "Cancellation normally unavailable after dispatch."),
    ("correct", "yes", "yes", "Consistent with the cancellation policy."),
    ("correct", "yes", "no", "Retrieved international_shipping.md; verify accepted source mapping."),
    ("correct", "yes", "yes", "International shipping answer; verify both cited policies."),
    ("correct", "yes", "yes", "Correct replacement guidance for wrong item."),
    ("correct", "yes", "yes", "Correct replacement guidance and refund alternative."),
    ("correct", "yes", "yes", "Correct refund estimate; verify policy wording."),
    ("correct", "yes", "yes", "Matches expected payment methods."),
    ("correct", "yes", "yes", "Correct discount-code rule and exception."),
    ("correct", "yes", "yes", "Appropriate investigation steps for missing items."),
    ("correct", "yes", "yes", "Matches warranty qualification."),
    ("correct", "yes", "yes", "Correct gift-card cash-exchange rule."),
    ("correct", "yes", "yes", "Correct privacy guidance."),
    ("correct", "yes", "not_applicable", "Appropriate uncertainty; verify cited policies lack an answer.")
]

assert len(df) == len(reviews) == 20, (
    f"Expected 20 rows, found {len(df)}"
)

for i, (verdict, supported, citation, notes) in enumerate(reviews):
    df.loc[i, "human_verdict"] = verdict
    df.loc[i, "source_supported"] = supported
    df.loc[i, "citation_correct"] = citation
    df.loc[i, "review_notes"] = notes

df.to_csv(path, index=False)

print("Saved preliminary review to:", path)
display(df[[
    "question",
    "human_verdict",
    "source_supported",
    "citation_correct",
    "review_notes"
]])

In [ ]:
import pandas as pd
from pathlib import Path

path = Path(
    "/content/drive/MyDrive/ShopAssist/data/evaluation/"
    "human_review_benchmark.csv"
)

df = pd.read_csv(path)

review_columns = [
    "human_verdict",
    "source_supported",
    "citation_correct",
    "review_notes"
]

# Explicitly set review columns to string/object-compatible values
for column in review_columns:
    df[column] = df[column].fillna("").astype(str)

df.to_csv(path, index=False)

# Reload to verify the saved file
check = pd.read_csv(path, dtype=str).fillna("")

print("File saved and verified.")
print("Rows:", len(check))
print("\nReview verdict counts:")
print(check["human_verdict"].value_counts().to_string())
print("\nMissing review labels:")
print((check[review_columns[:3]] == "").sum().to_string())

In [ ]:
import pandas as pd
from pathlib import Path

path = Path(
    "/content/drive/MyDrive/ShopAssist/data/evaluation/"
    "human_review_benchmark.csv"
)

df = pd.read_csv(path).fillna("")

total = len(df)

print("SHOPASSIST AI — PRELIMINARY EVALUATION")
print("=" * 45)
print(f"Total questions: {total}")

print("\nHuman verdict distribution:")
print(df["human_verdict"].value_counts().to_string())

print("\nPreliminary metrics:")
print(
    "Answer correctness:",
    f"{(df['human_verdict'] == 'correct').sum() / total * 100:.1f}%"
)
print(
    "Source support:",
    f"{(df['source_supported'] == 'yes').sum() / total * 100:.1f}%"
)

applicable = df["citation_correct"].isin(["yes", "no"])
if applicable.sum():
    citation_accuracy = (
        (df.loc[applicable, "citation_correct"] == "yes").sum()
        / applicable.sum()
        * 100
    )
    print(
        "Citation accuracy among applicable labels:",
        f"{citation_accuracy:.1f}%"
    )
    print("Applicable citation labels:", int(applicable.sum()))

print("\nReminder: these are preliminary, not independently verified metrics.")

In [ ]:
from pathlib import Path

policy_dir = Path(
    "/content/drive/MyDrive/ShopAssist/data/policies"
)

for filename in [
    "damaged_items.md",
    "shipping_policy.md",
    "international_shipping.md",
    "delivery_policy.md",
    "cancellation_policy.md",
]:
    path = policy_dir / filename
    print(f"\n{'=' * 60}")
    print(f"POLICY: {filename}")
    print("=" * 60)

    if path.exists():
        print(path.read_text(encoding="utf-8"))
    else:
        print("File not found.")

In [ ]:
import pandas as pd
from pathlib import Path

path = Path(
    "/content/drive/MyDrive/ShopAssist/data/evaluation/"
    "human_review_benchmark.csv"
)

df = pd.read_csv(path, dtype=str).fillna("")

# Q9 is the ninth row (zero-based index 8)
df.loc[8, "citation_correct"] = "yes"
df.loc[8, "review_notes"] = (
    "Verified: international_shipping.md explicitly confirms "
    "shipping to selected countries."
)

df.to_csv(path, index=False)

print("Updated Q9 citation review.")
print(df.loc[8, [
    "question",
    "retrieved_source",
    "citation_correct",
    "review_notes"
]].to_string())

In [ ]:
df = pd.read_csv(path, dtype=str).fillna("")

applicable = df["citation_correct"].isin(["yes", "no"])
correct_citations = (
    df.loc[applicable, "citation_correct"] == "yes"
).sum()

print("Applicable citations:", int(applicable.sum()))
print("Correct citations:", int(correct_citations))
print(
    "Citation accuracy:",
    f"{correct_citations / applicable.sum() * 100:.1f}%"
)

In [ ]:
from pathlib import Path

policy_dir = Path(
    "/content/drive/MyDrive/ShopAssist/data/policies"
)

files_to_check = [
    "returns_policy.md",
    "replacement_policy.md",
    "refund_policy.md",
    "payment_policy.md",
    "discount_policy.md",
    "missing_items.md",
    "warranty_policy.md",
    "gift_cards.md",
    "privacy_policy.md",
]

for filename in files_to_check:
    file_path = policy_dir / filename

    print(f"\n{'=' * 60}")
    print(f"POLICY: {filename}")
    print("=" * 60)

    if file_path.exists():
        print(file_path.read_text(encoding="utf-8"))
    else:
        print("FILE NOT FOUND")

In [ ]:
import pandas as pd
from pathlib import Path

path = Path(
    "/content/drive/MyDrive/ShopAssist/data/evaluation/"
    "human_review_benchmark.csv"
)

df = pd.read_csv(path, dtype=str).fillna("")

# Q20 is the final row
df.loc[19, "source_supported"] = "uncertain"
df.loc[19, "review_notes"] = (
    "The chatbot appropriately acknowledges missing information. "
    "The available policies do not specify whether an address can "
    "be changed after dispatch, so source support is uncertain."
)

df.to_csv(path, index=False)

print("Updated Q20.")
print(df.loc[19, [
    "question",
    "human_verdict",
    "source_supported",
    "citation_correct",
    "review_notes"
]].to_string(index=False))

In [ ]:
df = pd.read_csv(path, dtype=str).fillna("")

total = len(df)
correct_answers = (df["human_verdict"] == "correct").sum()

source_labels = df["source_supported"].str.lower()
source_yes = (source_labels == "yes").sum()
source_no = (source_labels == "no").sum()
source_uncertain = (source_labels == "uncertain").sum()

citation_labels = df["citation_correct"].str.lower()
citation_applicable = citation_labels.isin(["yes", "no"])
citation_correct = (citation_labels == "yes").sum()

print("SHOPASSIST AI — POLICY-REVIEWED EVALUATION")
print("=" * 48)
print(f"Questions reviewed: {total}")
print(f"Answers labelled correct: {correct_answers}/{total}")
print(f"Answer correctness: {correct_answers / total * 100:.1f}%")

print(f"\nSource supported: {source_yes}/{total}")
print(f"Source unsupported: {source_no}/{total}")
print(f"Source support uncertain: {source_uncertain}/{total}")

if citation_applicable.sum():
    print(
        "\nCitation accuracy:",
        f"{citation_correct / citation_applicable.sum() * 100:.1f}%"
    )
    print("Applicable citations:", int(citation_applicable.sum()))

In [ ]:
import pandas as pd
from pathlib import Path

project_root = Path("/content/drive/MyDrive/ShopAssist")
evaluation_dir = project_root / "data" / "evaluation"
evaluation_dir.mkdir(parents=True, exist_ok=True)

benchmark_path = evaluation_dir / "human_review_benchmark.csv"
df = pd.read_csv(benchmark_path, dtype=str).fillna("")

total = len(df)
correct = (df["human_verdict"] == "correct").sum()
partial = (df["human_verdict"] == "partially_correct").sum()
incorrect = (df["human_verdict"] == "incorrect").sum()

source_yes = (df["source_supported"] == "yes").sum()
source_no = (df["source_supported"] == "no").sum()
source_uncertain = (df["source_supported"] == "uncertain").sum()

citation_applicable = df["citation_correct"].isin(["yes", "no"])
citation_correct = (df.loc[citation_applicable, "citation_correct"] == "yes").sum()
citation_total = int(citation_applicable.sum())

metrics = pd.DataFrame([
    ["Questions reviewed", total, "Count"],
    ["Labelled correct", int(correct), "Count"],
    ["Preliminary answer correctness", round(correct / total * 100, 1), "%"],
    ["Source supported", int(source_yes), "Count"],
    ["Source unsupported", int(source_no), "Count"],
    ["Source uncertain", int(source_uncertain), "Count"],
    ["Citation correct", int(citation_correct), "Count"],
    ["Applicable citations", citation_total, "Count"],
    [
        "Citation accuracy",
        round(citation_correct / citation_total * 100, 1)
        if citation_total else 0,
        "%"
    ],
], columns=["metric", "value", "unit"])

output_path = evaluation_dir / "human_review_metrics.csv"
metrics.to_csv(output_path, index=False)

print("Saved metrics report:", output_path)
display(metrics)

In [ ]:
from pathlib import Path

readme_path = Path("/content/ShopAssist/README.md")
readme = readme_path.read_text(encoding="utf-8")

section_heading = "## Human-Reviewed Answer Evaluation"

new_section = """## Human-Reviewed Answer Evaluation

ShopAssist AI was evaluated using a benchmark of 20 customer questions covering returns, delivery, cancellations, international shipping, replacements, refunds, payments, discounts, missing items, warranties, gift cards, privacy, and an out-of-scope address-change question.

The benchmark compares generated responses with expected answers and relevant policy documents. Responses were reviewed using three criteria: answer correctness, policy-source support, and citation correctness.

### Preliminary Results

| Metric | Result |
|---|---:|
| Questions reviewed | 20 |
| Answers labelled correct | 20/20 (100%) |
| Answers marked as source-supported | 19/20 (95%) |
| Answers with uncertain source support | 1/20 (5%) |
| Citation accuracy among applicable labels | 19/19 (100%) |

**Interpretation:** These are preliminary, human-reviewed results based on the current benchmark labels. They should not be interpreted as independently validated model accuracy or as evidence of performance across all possible customer queries.

One question asked whether a delivery address could be changed after dispatch. The available policies did not specify whether this was possible, and the chatbot acknowledged the information gap rather than asserting an unsupported policy.

Citation accuracy excludes that question because its citation label was marked `not_applicable`. The international-shipping source was also reviewed against the policy documents, which confirm shipping to selected countries.

### Evaluation Files

The evaluation artifacts are stored in `data/evaluation/`:

- `evaluation_questions.csv` — benchmark questions, expected answers, and expected sources.
- `rag_evaluation_results.csv` — recorded retrieval and generated-answer results.
- `improved_evaluation_report.csv` — additional retrieval and phrase-check indicators.
- `human_review_benchmark.csv` — human-review labels and notes.
- `human_review_metrics.csv` — summary of the preliminary human-review metrics.

The benchmark is small and reflects a limited set of policy questions. Further evaluation should include more paraphrases, ambiguous queries, unsupported questions, and independent review of answer claims and citations.

"""

if section_heading in readme:
    print("The evaluation section already exists. No changes made.")
elif "## Automated Tests" in readme:
    readme = readme.replace(
        "## Automated Tests",
        new_section + "## Automated Tests",
        1
    )
    readme_path.write_text(readme, encoding="utf-8")
    print("README updated successfully.")
else:
    print("Could not find the insertion point. README was not changed.")

print("\nREADME path:", readme_path)
print("Evaluation section present:", section_heading in readme_path.read_text(encoding="utf-8"))

In [ ]:
from pathlib import Path
import shutil

drive_eval = Path(
    "/content/drive/MyDrive/ShopAssist/data/evaluation"
)
repo_eval = Path(
    "/content/ShopAssist/data/evaluation"
)

repo_eval.mkdir(parents=True, exist_ok=True)

files_to_copy = [
    "improved_evaluation_report.csv",
    "human_review_benchmark.csv",
    "human_review_metrics.csv",
]

for filename in files_to_copy:
    source = drive_eval / filename
    destination = repo_eval / filename

    if source.exists():
        shutil.copy2(source, destination)
        print(f"Copied: {filename}")
    else:
        print(f"NOT FOUND: {source}")

print("\nEvaluation files now in repository:")
for file in sorted(repo_eval.glob("*.csv")):
    print(f"- {file.name}")

In [ ]:
import subprocess

result = subprocess.run(
    ["git", "status", "--short"],
    cwd="/content/ShopAssist",
    capture_output=True,
    text=True
)

print(result.stdout)

In [ ]:
import subprocess

repo = "/content/ShopAssist"

files = [
    "README.md",
    "data/evaluation/human_review_benchmark.csv",
    "data/evaluation/human_review_metrics.csv",
    "data/evaluation/improved_evaluation_report.csv",
]

# Stage only the intended files
subprocess.run(
    ["git", "add", *files],
    cwd=repo,
    check=True
)

# Review staged changes
result = subprocess.run(
    ["git", "diff", "--cached", "--stat"],
    cwd=repo,
    capture_output=True,
    text=True,
    check=True
)

print("Staged changes:")
print(result.stdout)

print("\nStaged file list:")
result = subprocess.run(
    ["git", "diff", "--cached", "--name-only"],
    cwd=repo,
    capture_output=True,
    text=True,
    check=True
)
print(result.stdout)

In [ ]:
import subprocess
from google.colab import userdata

repo = "/content/ShopAssist"

# Commit the staged files
commit = subprocess.run(
    [
        "git", "commit", "-m",
        "Add human-reviewed evaluation results"
    ],
    cwd=repo,
    capture_output=True,
    text=True
)

print(commit.stdout)

if commit.returncode != 0:
    print(commit.stderr)
    raise RuntimeError("Commit failed; inspect the output above.")

# Retrieve the GitHub token securely
token = userdata.get("GITHUB_TOKEN")

if not token:
    raise RuntimeError("GITHUB_TOKEN was not available in Colab Secrets.")

# Push without changing the saved remote URL
push = subprocess.run(
    [
        "git", "push",
        "https://x-access-token:" + token
        + "@github.com/DhruviPatadia/ShopAssist.git",
        "HEAD"
    ],
    cwd=repo,
    capture_output=True,
    text=True
)

print("\nPush output:")
print(push.stdout)

if push.returncode != 0:
    print(push.stderr)
    raise RuntimeError("Push failed; inspect the output above.")

print("Successfully pushed the evaluation updates to GitHub.")

In [ ]:
from pathlib import Path
import subprocess

drive_notebook = Path(
    "/content/drive/MyDrive/ShopAssist/notebooks/02_chatbot_app.ipynb"
)

repo_notebook = Path(
    "/content/ShopAssist/notebooks/02_chatbot_app.ipynb"
)

print("GOOGLE DRIVE")
print("Notebook exists:", drive_notebook.exists())
if drive_notebook.exists():
    print("Size:", round(drive_notebook.stat().st_size / 1024, 1), "KB")

print("\nGITHUB CLONE")
print("Notebook exists:", repo_notebook.exists())
if repo_notebook.exists():
    print("Size:", round(repo_notebook.stat().st_size / 1024, 1), "KB")

print("\nGIT TRACKING")
result = subprocess.run(
    ["git", "ls-files", "notebooks/02_chatbot_app.ipynb"],
    cwd="/content/ShopAssist",
    capture_output=True,
    text=True
)
print(result.stdout.strip() or "Notebook is not tracked by Git.")

In [ ]:
import shutil

if drive_notebook.exists():
    repo_notebook.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(drive_notebook, repo_notebook)
    print("Notebook copied into the GitHub repository clone.")
else:
    print("Notebook not found in Drive. Do not create a replacement yet.")

In [ ]:
import subprocess
from google.colab import userdata

repo = "/content/ShopAssist"
notebook_path = "notebooks/02_chatbot_app.ipynb"

subprocess.run(
    ["git", "add", notebook_path],
    cwd=repo,
    check=True
)

status = subprocess.run(
    ["git", "status", "--short"],
    cwd=repo,
    capture_output=True,
    text=True,
    check=True
)
print(status.stdout)

In [ ]:
import subprocess
from google.colab import userdata

repo = "/content/ShopAssist"
token = userdata.get("GITHUB_TOKEN")

if not token:
    raise RuntimeError("GITHUB_TOKEN not found in Colab Secrets.")

subprocess.run(
    ["git", "commit", "-m", "Add chatbot application notebook"],
    cwd=repo,
    check=True
)

push = subprocess.run(
    [
        "git", "push",
        "https://x-access-token:" + token
        + "@github.com/DhruviPatadia/ShopAssist.git",
        "HEAD"
    ],
    cwd=repo,
    capture_output=True,
    text=True
)

print(push.stdout)
if push.returncode != 0:
    print(push.stderr)
    raise RuntimeError("Push failed.")

print("Notebook pushed successfully.")

In [ ]:
from pathlib import Path

requirements_path = Path("/content/ShopAssist/requirements.txt")

if requirements_path.exists():
    print(requirements_path.read_text())
else:
    print("requirements.txt not found in /content/ShopAssist")

In [ ]:
from pathlib import Path

project = Path("/content/ShopAssist")

files_to_check = [
    "app/gradio_app.py",
    "src/retrieval.py",
    "src/chatbot.py",
    "requirements.txt",
    "README.md",
]

for filename in files_to_check:
    path = project / filename
    print(f"{'FOUND' if path.exists() else 'MISSING'}: {filename}")

policy_dir = project / "data" / "policies"
if policy_dir.exists():
    policies = list(policy_dir.glob("*.md"))
    print(f"\nPolicy documents found: {len(policies)}")
else:
    print("\nMISSING: data/policies/")

In [ ]:
from pathlib import Path

app_file = Path("/content/ShopAssist/app/gradio_app.py")

print(app_file.read_text()[:5000])

In [ ]:
from pathlib import Path

project_dir = Path("/content/ShopAssist")

deployment_app = '''from pathlib import Path
import os

import gradio as gr

from src.retrieval import load_policies, build_retrieval_index
from src.chatbot import create_chatbot

PROJECT_DIR = Path(__file__).resolve().parent


def build_app():
    policy_dir = PROJECT_DIR / "data" / "policies"
    documents_df = load_policies(policy_dir)

    embedding_model, faiss_index = build_retrieval_index(documents_df)

    api_key = os.environ.get("GEMINI_API_KEY", "").strip()

    chatbot = create_chatbot(
        documents_df=documents_df,
        embedding_model=embedding_model,
        faiss_index=faiss_index,
        api_key=api_key
    )

    def respond(message, history):
        if not message or not message.strip():
            return "Please enter a question."

        try:
            return chatbot(message.strip(), history=history)
        except Exception:
            return (
                "Sorry, something went wrong. "
                "Please try asking your question again."
            )

    return gr.ChatInterface(
        fn=respond,
        title="ShopAssist AI",
        description=(
            "Your e-commerce support assistant. "
            "Ask about delivery, returns, refunds, replacements, and more. "
            "Answers are grounded in the available policy documents."
        ),
        examples=[
            "How long does standard delivery take?",
            "How can I return an item?",
            "My item arrived damaged. What should I do?",
            "Can I cancel my order after dispatch?"
        ]
    )


if __name__ == "__main__":
    app = build_app()
    app.launch()
'''

target = project_dir / "app.py"
target.write_text(deployment_app, encoding="utf-8")

print("Created:", target)
print("Original app/gradio_app.py has not been changed.")
print("Deployment entry point exists:", target.exists())

In [ ]:
from pathlib import Path

root = Path("/content/ShopAssist")

print("=== requirements.txt ===")
print((root / "requirements.txt").read_text())

print("\n=== README.md first 25 lines ===")
readme_lines = (root / "README.md").read_text().splitlines()
print("\n".join(readme_lines[:25]))

In [ ]:
from pathlib import Path

readme_path = Path("/content/ShopAssist/README.md")
content = readme_path.read_text(encoding="utf-8")

if content.startswith("---\n"):
    print("README already starts with a configuration header.")
else:
    header = """---
title: ShopAssist AI
emoji: 🛍️
colorFrom: blue
colorTo: indigo
sdk: gradio
sdk_version: 5.49.1
app_file: app.py
pinned: false
---

"""
    readme_path.write_text(header + content, encoding="utf-8")
    print("Added Hugging Face configuration to README.md")

print("\nREADME preview:")
print("\n".join(readme_path.read_text(encoding="utf-8").splitlines()[:15]))

In [ ]:
from pathlib import Path

root = Path("/content/ShopAssist")

required = [
    "app.py",
    "requirements.txt",
    "README.md",
    "src/retrieval.py",
    "src/chatbot.py",
]

for name in required:
    print(f"{'✅' if (root / name).is_file() else '❌'} {name}")

policies = list((root / "data/policies").glob("*.md"))
print(f"\nPolicy documents: {len(policies)}")

print("\nGit status:")
import subprocess
result = subprocess.run(
    ["git", "status", "--short"],
    cwd=root,
    capture_output=True,
    text=True
)
print(result.stdout or "No uncommitted changes.")

In [ ]:
!pip -q install -U huggingface_hub

In [ ]:
from getpass import getpass
from huggingface_hub import login

hf_token = getpass("Enter your Hugging Face access token: ")
login(token=hf_token, add_to_git_credential=False)
del hf_token

print("Hugging Face authentication completed.")

In [ ]:
from huggingface_hub import get_token, whoami

token = get_token()

if token:
    try:
        account = whoami()
        print("Already authenticated with Hugging Face.")
        print("Account:", account.get("name", "Authenticated account"))
        print("We can try using this existing login.")
    except Exception:
        print("A token exists, but authentication could not be verified.")
else:
    print("No existing Hugging Face token was found.")

In [ ]:
import subprocess
from pathlib import Path

project = Path("/content/ShopAssist")

# Check whether the files exist locally
for name in ["app.py", "README.md"]:
    print(f"{name} exists locally:", (project / name).exists())

# Check Git status
result = subprocess.run(
    ["git", "status", "--short"],
    cwd=project,
    capture_output=True,
    text=True
)

print("\nGit status:")
print(result.stdout if result.stdout.strip() else "Working tree is clean.")

In [ ]:
import subprocess
from pathlib import Path

project = Path("/content/ShopAssist")

def run_git(args):
    result = subprocess.run(
        ["git", *args],
        cwd=project,
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        print(result.stderr)
        raise RuntimeError("Git command failed.")
    return result.stdout.strip()

# Stage only the deployment files
run_git(["add", "app.py", "README.md"])

# Commit the staged changes
status = run_git(["diff", "--cached", "--name-only"])
print("Files staged for commit:")
print(status)

if status:
    result = subprocess.run(
        ["git", "commit", "-m", "Prepare ShopAssist for Render deployment"],
        cwd=project,
        capture_output=True,
        text=True
    )
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
        raise RuntimeError("Commit failed.")
else:
    print("No staged changes to commit.")

In [ ]:
from google.colab import userdata

try:
    github_token = userdata.get("GITHUB_TOKEN")
    print("GitHub token is available in Colab Secrets.")
    del github_token
except Exception:
    print("GITHUB_TOKEN is not available in Colab Secrets.")

In [ ]:
from google.colab import userdata
import subprocess
from pathlib import Path

project = Path("/content/ShopAssist")
token = userdata.get("GITHUB_TOKEN")

result = subprocess.run(
    [
        "git", "push",
        f"https://x-access-token:{token}@github.com/DhruviPatadia/ShopAssist.git",
        "HEAD:main"
    ],
    cwd=project,
    capture_output=True,
    text=True
)

print("Return code:", result.returncode)
print(result.stdout)

if result.returncode != 0:
    print("Push failed. Error details:")
    print(result.stderr)
else:
    print("Deployment files pushed successfully!")

In [ ]:
from pathlib import Path

project = Path("/content/ShopAssist")
app_path = project / "app.py"

content = app_path.read_text(encoding="utf-8")

old = '''if __name__ == "__main__":
    app = build_app()
    app.launch()
'''

new = '''if __name__ == "__main__":
    app = build_app()
    port = int(os.environ.get("PORT", "10000"))
    app.launch(
        server_name="0.0.0.0",
        server_port=port
    )
'''

if old not in content:
    print("Expected launch block not found. No changes made.")
else:
    app_path.write_text(content.replace(old, new), encoding="utf-8")
    print("Updated app.py to use Render's port.")
    print(app_path.read_text(encoding="utf-8")[-300:])

In [ ]:
import subprocess
from pathlib import Path

project = Path("/content/ShopAssist")

def git_run(args):
    result = subprocess.run(
        ["git", *args],
        cwd=project,
        capture_output=True,
        text=True
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr or result.stdout)
    return result.stdout.strip()

git_run(["add", "app.py"])

print(git_run([
    "commit", "-m", "Fix Render web server port binding"
]))

In [ ]:
from google.colab import userdata
import subprocess

token = userdata.get("GITHUB_TOKEN")

result = subprocess.run(
    [
        "git", "push",
        f"https://x-access-token:{token}@github.com/DhruviPatadia/ShopAssist.git",
        "HEAD:main"
    ],
    cwd="/content/ShopAssist",
    capture_output=True,
    text=True
)

del token

print("Return code:", result.returncode)
print(result.stdout)

if result.returncode != 0:
    print(result.stderr)
else:
    print("Port-binding fix pushed successfully.")

In [ ]:
from pathlib import Path

project_dir = Path("/content/ShopAssist")

# Inspect current retrieval implementation
retrieval_file = project_dir / "src" / "retrieval.py"

print("===== CURRENT RETRIEVAL CODE =====")
print(retrieval_file.read_text(encoding="utf-8"))

# Find evaluation CSV files
print("\n===== EVALUATION FILES =====")
for file_path in sorted((project_dir / "data" / "evaluation").glob("*.csv")):
    print(f"\nFile: {file_path.name}")
    print("Columns and sample rows:")
    import pandas as pd
    df = pd.read_csv(file_path)
    print("Columns:", df.columns.tolist())
    print(df.head(3).to_string(index=False))

In [ ]:
import os
from google import genai
from google.genai import types

api_key = os.environ.get("GEMINI_API_KEY")

# If the key is stored in Colab Secrets, load it without printing it.
if not api_key:
    from google.colab import userdata
    api_key = userdata.get("GEMINI_API_KEY")

client = genai.Client(api_key=api_key)

response = client.models.embed_content(
    model="gemini-embedding-001",
    contents="How long do I have to return an item?",
    config=types.EmbedContentConfig(
        task_type="RETRIEVAL_QUERY",
        output_dimensionality=768
    )
)

embedding = response.embeddings[0].values

print("Embedding API test: successful")
print("Embedding dimensions:", len(embedding))
print("All values finite:", all(__import__("math").isfinite(x) for x in embedding))

In [ ]:
from pathlib import Path

project_dir = Path("/content/ShopAssist")
new_file = project_dir / "src" / "retrieval_gemini.py"

code = r'''
from pathlib import Path

import faiss
import numpy as np
import pandas as pd
from google import genai
from google.genai import types


EMBEDDING_MODEL = "gemini-embedding-001"
EMBEDDING_DIMENSIONS = 768


def load_policies(policy_dir):
    """Load Markdown policy documents."""
    policy_dir = Path(policy_dir)
    documents = []

    for file_path in sorted(policy_dir.glob("*.md")):
        documents.append({
            "source": file_path.name,
            "text": file_path.read_text(encoding="utf-8")
        })

    if not documents:
        raise ValueError(f"No Markdown policy files found in {policy_dir}")

    return pd.DataFrame(documents)


def _embed_texts(client, texts, task_type):
    """Generate and normalize hosted embeddings."""
    if not texts:
        return np.empty((0, EMBEDDING_DIMENSIONS), dtype="float32")

    response = client.models.embed_content(
        model=EMBEDDING_MODEL,
        contents=texts,
        config=types.EmbedContentConfig(
            task_type=task_type,
            output_dimensionality=EMBEDDING_DIMENSIONS
        )
    )

    if not response.embeddings or len(response.embeddings) != len(texts):
        raise ValueError("The embedding API returned an unexpected number of vectors.")

    vectors = np.asarray(
        [item.values for item in response.embeddings],
        dtype="float32"
    )

    if vectors.shape != (len(texts), EMBEDDING_DIMENSIONS):
        raise ValueError(f"Unexpected embedding shape: {vectors.shape}")

    if not np.isfinite(vectors).all():
        raise ValueError("Embeddings contain non-finite values.")

    norms = np.linalg.norm(vectors, axis=1, keepdims=True)
    if np.any(norms == 0):
        raise ValueError("The embedding API returned a zero-length vector.")

    return np.ascontiguousarray(vectors / norms, dtype="float32")


def build_retrieval_index(documents_df, api_key=None):
    """Build a FAISS index from Gemini policy embeddings."""
    import os

    api_key = api_key or os.environ.get("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY was not provided.")

    client = genai.Client(api_key=api_key)

    embeddings = _embed_texts(
        client,
        documents_df["text"].tolist(),
        task_type="RETRIEVAL_DOCUMENT"
    )

    index = faiss.IndexFlatIP(EMBEDDING_DIMENSIONS)
    index.add(embeddings)

    return client, index


def search_policies(query, documents_df, client, index, top_k=3):
    """Return the highest-ranked policy documents and cosine-style scores."""
    columns = ["rank", "source", "similarity"]

    if not query or not query.strip():
        return pd.DataFrame(columns=columns)

    if index.ntotal != len(documents_df):
        raise ValueError("Index size does not match the policy document count.")

    query_embedding = _embed_texts(
        client,
        [query.strip()],
        task_type="RETRIEVAL_QUERY"
    )

    k = min(max(int(top_k), 1), len(documents_df))
    scores, indices = index.search(query_embedding, k)

    results = []
    for rank, (score, idx) in enumerate(zip(scores[0], indices[0]), start=1):
        if idx >= 0:
            results.append({
                "rank": rank,
                "source": documents_df.iloc[idx]["source"],
                "similarity": float(score)
            })

    return pd.DataFrame(results, columns=columns)
'''

new_file.write_text(code, encoding="utf-8")
print("Created:", new_file)
print("Original retrieval.py preserved:", (project_dir / "src" / "retrieval.py").exists())

In [ ]:
import os
import pandas as pd
from pathlib import Path
from IPython.display import display

from src.retrieval_gemini import (
    load_policies,
    build_retrieval_index,
    search_policies
)

project_dir = Path("/content/ShopAssist")

api_key = os.environ.get("GEMINI_API_KEY")
if not api_key:
    from google.colab import userdata
    api_key = userdata.get("GEMINI_API_KEY")

documents_df = load_policies(project_dir / "data" / "policies")
client, index = build_retrieval_index(documents_df, api_key=api_key)

questions = pd.read_csv(
    project_dir / "data" / "evaluation" / "evaluation_questions.csv"
)

rows = []
for _, item in questions.iterrows():
    results = search_policies(
        item["question"], documents_df, client, index, top_k=3
    )

    expected = item["expected_source"]
    matches = results.index[results["source"] == expected].tolist()
    rank = int(matches[0] + 1) if matches else None

    rows.append({
        "id": item["id"],
        "question": item["question"],
        "expected_source": expected,
        "top_1_source": results.iloc[0]["source"] if not results.empty else None,
        "expected_source_rank": rank,
        "reciprocal_rank": 1 / rank if rank else 0,
        "expected_source_in_top_3": rank is not None
    })

results_df = pd.DataFrame(rows)

mrr = results_df["reciprocal_rank"].mean()
recall_at_3 = results_df["expected_source_in_top_3"].mean()

print("Documents indexed:", index.ntotal)
print("Evaluation questions:", len(results_df))
print(f"Gemini embedding MRR: {mrr:.4f}")
print(f"Gemini embedding Recall@3: {recall_at_3:.2%}")
display(results_df)

In [ ]:
from pathlib import Path
import os

print("Current working directory:", os.getcwd())

project_dir = Path("/content/ShopAssist")
print("Project exists:", project_dir.exists())
print("Retrieval file exists:", (project_dir / "src" / "retrieval_gemini.py").exists())
print("Source directory exists:", (project_dir / "src").exists())

if (project_dir / "src").exists():
    print("Files in src:")
    for file in sorted((project_dir / "src").iterdir()):
        print("-", file.name)

In [ ]:
import sys
import importlib
from pathlib import Path

project_dir = Path("/content/ShopAssist").resolve()

# Ensure Colab can import the project
if str(project_dir) not in sys.path:
    sys.path.insert(0, str(project_dir))

# Confirm Python sees the source file
file_path = project_dir / "src" / "retrieval_gemini.py"
assert file_path.exists(), f"File not found: {file_path}"

# Import the module
import src.retrieval_gemini as retrieval_gemini
importlib.reload(retrieval_gemini)

print("Import successful!")
print("Loaded from:", retrieval_gemini.__file__)

In [ ]:
import os
import pandas as pd
from pathlib import Path
from IPython.display import display

from src.retrieval_gemini import (
    load_policies,
    build_retrieval_index,
    search_policies
)

project_dir = Path("/content/ShopAssist")

api_key = os.environ.get("GEMINI_API_KEY")
if not api_key:
    from google.colab import userdata
    api_key = userdata.get("GEMINI_API_KEY")

documents_df = load_policies(project_dir / "data" / "policies")
client, index = build_retrieval_index(documents_df, api_key=api_key)

questions = pd.read_csv(
    project_dir / "data" / "evaluation" / "evaluation_questions.csv"
)

rows = []

for _, item in questions.iterrows():
    results = search_policies(
        item["question"],
        documents_df,
        client,
        index,
        top_k=3
    )

    expected = item["expected_source"]
    matches = results.index[results["source"] == expected].tolist()
    rank = int(matches[0] + 1) if matches else None

    rows.append({
        "id": item["id"],
        "question": item["question"],
        "expected_source": expected,
        "top_1_source": results.iloc[0]["source"] if not results.empty else None,
        "expected_source_rank": rank,
        "reciprocal_rank": 1 / rank if rank else 0,
        "expected_source_in_top_3": rank is not None
    })

results_df = pd.DataFrame(rows)

print("Documents indexed:", index.ntotal)
print("Evaluation questions:", len(results_df))
print(f"Gemini embedding MRR: {results_df['reciprocal_rank'].mean():.4f}")
print(f"Gemini embedding Recall@3: {results_df['expected_source_in_top_3'].mean():.2%}")

display(results_df)

In [ ]:
import pandas as pd
from IPython.display import display

# Exclude questions with no expected source from the primary metrics.
valid_df = results_df.dropna(subset=["expected_source"]).copy()

mrr_valid = valid_df["reciprocal_rank"].mean()
recall_valid = valid_df["expected_source_in_top_3"].mean()
top1_valid = (
    valid_df["expected_source_rank"].eq(1).mean()
)

print("===== FAIR RETRIEVAL METRICS =====")
print("Questions with expected sources:", len(valid_df))
print(f"MRR: {mrr_valid:.4f}")
print(f"Recall@3: {recall_valid:.2%}")
print(f"Top-1 accuracy: {top1_valid:.2%}")

# Inspect the international-shipping confusion.
print("\n===== QUESTIONS 9 AND 10 =====")
for question_id in [9, 10]:
    item = questions.loc[questions["id"] == question_id].iloc[0]
    ranked = search_policies(
        item["question"], documents_df, client, index, top_k=3
    )

    print(f"\nQ{question_id}: {item['question']}")
    print("Expected source:", item["expected_source"])
    display(ranked)

# Inspect question 20 separately.
print("\n===== QUESTION 20: MISSING EXPECTED SOURCE =====")
item = questions.loc[questions["id"] == 20].iloc[0]
print("Question:", item["question"])
print("Expected source:", item["expected_source"])

display(
    search_policies(
        item["question"], documents_df, client, index, top_k=3
    )
)

In [ ]:
from pathlib import Path

project_dir = Path("/content/ShopAssist")

for relative_path in [
    "src/chatbot.py",
    "app.py",
]:
    path = project_dir / relative_path
    print(f"\n{'=' * 20} {relative_path} {'=' * 20}")
    print(path.read_text(encoding="utf-8"))

In [ ]:
from pathlib import Path

project_dir = Path("/content/ShopAssist")
new_file = project_dir / "src" / "chatbot_gemini.py"

code = r'''
import os

from google import genai

from src.retrieval_gemini import search_policies


def create_chatbot(
    documents_df,
    embedding_client,
    faiss_index,
    api_key=None,
    model_name="gemini-3.5-flash-lite"
):
    """Create a policy-grounded chatbot using hosted embeddings."""

    api_key = api_key or os.environ.get("GEMINI_API_KEY", "").strip()
    if not api_key:
        raise ValueError("Gemini API key not found.")

    generation_client = genai.Client(api_key=api_key)

    def answer_question(question, history=None):
        if not question or not question.strip():
            return "Please enter a question."

        results = search_policies(
            question,
            documents_df,
            embedding_client,
            faiss_index,
            top_k=3
        )

        policy_context = []
        for _, row in results.iterrows():
            matching = documents_df.loc[
                documents_df["source"] == row["source"], "text"
            ]
            if not matching.empty:
                policy_context.append(
                    f"Source: {row['source']}\n{matching.iloc[0]}"
                )

        context_text = "\n\n".join(policy_context)
        history_text = ""

        for item in (history or [])[-6:]:
            if isinstance(item, dict):
                role = item.get("role", "")
                content = item.get("content", "")
                if role in ("user", "assistant") and isinstance(content, str):
                    history_text += f"{role.capitalize()}: {content}\n"
            elif isinstance(item, (list, tuple)) and len(item) == 2:
                user_text, assistant_text = item
                if user_text:
                    history_text += f"User: {user_text}\n"
                if assistant_text:
                    history_text += f"Assistant: {assistant_text}\n"

        prompt = f"""
You are ShopAssist AI, an e-commerce customer support assistant.

Answer using only the policy documents supplied below. Use conversation
history to understand follow-up questions, but do not treat it as policy.

Rules:
1. Do not invent policies, deadlines, exceptions, or guarantees.
2. If the policies do not answer the question, say so clearly.
3. Give concise, helpful next steps when supported by the policies.
4. Cite relevant policy filenames, for example (Source: returns_policy.md).
5. Do not claim to have completed an action or contacted support.
6. Never ask for passwords or full card numbers.

Relevant policy documents:
{context_text if context_text else "No relevant policy documents were retrieved."}

Recent conversation:
{history_text if history_text else "No previous conversation."}

Current customer question:
{question.strip()}
"""

        try:
            response = generation_client.models.generate_content(
                model=model_name,
                contents=prompt
            )
            answer = response.text
            return answer if answer else (
                "I couldn't generate an answer. Please try again."
            )
        except Exception as error:
            error_text = str(error).lower()
            if "429" in error_text or "resource_exhausted" in error_text:
                return (
                    "The AI service has reached its current usage limit. "
                    "Please try again later."
                )
            return (
                "Sorry, I couldn't process your question right now. "
                "Please try again later."
            )

    return answer_question
'''

new_file.write_text(code, encoding="utf-8")
print("Created:", new_file)
print("Original chatbot preserved:",
      (project_dir / "src" / "chatbot.py").exists())

In [ ]:
from pathlib import Path

project_dir = Path("/content/ShopAssist")
new_file = project_dir / "app_gemini.py"

code = r'''
from pathlib import Path
import os

import gradio as gr

from src.retrieval_gemini import load_policies, build_retrieval_index
from src.chatbot_gemini import create_chatbot

PROJECT_DIR = Path(__file__).resolve().parent


def build_app():
    api_key = os.environ.get("GEMINI_API_KEY", "").strip()
    if not api_key:
        raise ValueError("Set GEMINI_API_KEY in the hosting environment.")

    policy_dir = PROJECT_DIR / "data" / "policies"
    documents_df = load_policies(policy_dir)

    embedding_client, faiss_index = build_retrieval_index(
        documents_df, api_key=api_key
    )

    chatbot = create_chatbot(
        documents_df=documents_df,
        embedding_client=embedding_client,
        faiss_index=faiss_index,
        api_key=api_key
    )

    def respond(message, history):
        if not message or not message.strip():
            return "Please enter a question."
        return chatbot(message.strip(), history=history)

    return gr.ChatInterface(
        fn=respond,
        title="ShopAssist AI",
        description=(
            "Your e-commerce support assistant. Ask about delivery, returns, "
            "refunds, replacements, and more. Answers use the available policies."
        ),
        examples=[
            "How long does standard delivery take?",
            "How can I return an item?",
            "My item arrived damaged. What should I do?",
            "Can I cancel my order after dispatch?"
        ]
    )


if __name__ == "__main__":
    app = build_app()
    port = int(os.environ.get("PORT", "10000"))
    app.launch(server_name="0.0.0.0", server_port=port)
'''

new_file.write_text(code, encoding="utf-8")
print("Created:", new_file)

In [ ]:
import os
from pathlib import Path

from src.retrieval_gemini import (
    load_policies,
    build_retrieval_index,
    search_policies
)
from src.chatbot_gemini import create_chatbot

project_dir = Path("/content/ShopAssist")

api_key = os.environ.get("GEMINI_API_KEY")
if not api_key:
    from google.colab import userdata
    api_key = userdata.get("GEMINI_API_KEY")

documents_df = load_policies(project_dir / "data" / "policies")
embedding_client, faiss_index = build_retrieval_index(
    documents_df, api_key=api_key
)

question = "How long does standard delivery take?"
retrieved = search_policies(
    question, documents_df, embedding_client, faiss_index, top_k=3
)

print("Retrieved policy sources:")
print(retrieved[["rank", "source", "similarity"]].to_string(index=False))

chatbot = create_chatbot(
    documents_df=documents_df,
    embedding_client=embedding_client,
    faiss_index=faiss_index,
    api_key=api_key
)

answer = chatbot(question)
print("\nChatbot answer:")
print(answer)

In [ ]:
import os

if not os.environ.get("GEMINI_API_KEY"):
    from google.colab import userdata
    os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")

print("Gemini API key available:", bool(os.environ.get("GEMINI_API_KEY")))

In [ ]:
from app_gemini import build_app

app = build_app()

print("Gradio app initialisation: successful")
print("App type:", type(app).__name__)

In [ ]:
from pathlib import Path
import os
import sys

project_dir = Path("/content/ShopAssist").resolve()

if str(project_dir) not in sys.path:
    sys.path.insert(0, str(project_dir))

from app_gemini import build_app

app = build_app()

print("Gradio app initialisation: successful")
print("App type:", type(app).__name__)
print("Hosted embedding module:", "src.retrieval_gemini")
print("Local Sentence Transformers required by app_gemini.py: No")

In [ ]:
from pathlib import Path
import subprocess

project_dir = Path("/content/ShopAssist")

print("===== REQUIREMENTS =====")
print((project_dir / "requirements.txt").read_text(encoding="utf-8"))

print("\n===== GIT STATUS =====")
result = subprocess.run(
    ["git", "status", "--short"],
    cwd=project_dir,
    capture_output=True,
    text=True
)
print(result.stdout or "No uncommitted changes.")
print(result.stderr)

In [ ]:
from pathlib import Path

project_dir = Path("/content/ShopAssist")

requirements = """faiss-cpu
numpy
pandas
google-genai
gradio
"""

file_path = project_dir / "requirements-render.txt"
file_path.write_text(requirements, encoding="utf-8")

print("Created:", file_path)
print("\nDeployment dependencies:")
print(file_path.read_text(encoding="utf-8"))

In [ ]:
import importlib.util

modules = {
    "faiss": "faiss",
    "numpy": "numpy",
    "pandas": "pandas",
    "google.genai": "google.genai",
    "gradio": "gradio",
}

print("===== DEPENDENCY CHECK =====")

for package, module in modules.items():
    available = importlib.util.find_spec(module) is not None
    print(f"{package}: {'available' if available else 'MISSING'}")

In [ ]:
from pathlib import Path
import subprocess
import sys
import py_compile

project_dir = Path("/content/ShopAssist")

print("===== 1. CHECK PYTHON SYNTAX =====")

files_to_check = [
    "src/retrieval.py",
    "src/chatbot.py",
    "src/retrieval_gemini.py",
    "src/chatbot_gemini.py",
    "app.py",
    "app_gemini.py",
]

for relative_path in files_to_check:
    py_compile.compile(
        str(project_dir / relative_path),
        doraise=True
    )
    print(f"PASS: {relative_path}")

print("\n===== 2. RUN EXISTING RETRIEVAL TESTS =====")

result = subprocess.run(
    [
        sys.executable, "-m", "pytest",
        str(project_dir / "tests" / "test_retrieval.py"),
        "-v"
    ],
    cwd=project_dir,
    capture_output=True,
    text=True
)

print(result.stdout)
if result.stderr:
    print(result.stderr)

print("Pytest exit code:", result.returncode)

if result.returncode != 0:
    print("Tests failed. Do not push the deployment changes yet.")
else:
    print("Existing retrieval tests passed.")

In [ ]:
from pathlib import Path
import subprocess

project_dir = Path("/content/ShopAssist")

files_to_commit = [
    "app_gemini.py",
    "src/chatbot_gemini.py",
    "src/retrieval_gemini.py",
    "requirements-render.txt",
]

print("===== FILES TO COMMIT =====")
for relative_path in files_to_commit:
    path = project_dir / relative_path
    print(f"{'EXISTS' if path.is_file() else 'MISSING'}: {relative_path}")

print("\n===== GIT STATUS =====")
result = subprocess.run(
    ["git", "status", "--short"],
    cwd=project_dir,
    capture_output=True,
    text=True
)
print(result.stdout)

In [ ]:
import subprocess
from pathlib import Path

project_dir = Path("/content/ShopAssist")

files_to_commit = [
    "app_gemini.py",
    "requirements-render.txt",
    "src/chatbot_gemini.py",
    "src/retrieval_gemini.py",
]

def run_git(args):
    result = subprocess.run(
        ["git"] + args,
        cwd=project_dir,
        capture_output=True,
        text=True
    )
    print(result.stdout)
    if result.stderr:
        print(result.stderr)
    if result.returncode != 0:
        raise RuntimeError(f"Git command failed: {args}")
    return result

# Stage only the new deployment files.
run_git(["add"] + files_to_commit)

# Create the commit.
run_git([
    "commit",
    "-m",
    "Add hosted embedding deployment"
])

print("Commit created successfully.")

In [ ]:
import subprocess
from pathlib import Path
from google.colab import userdata

project_dir = Path("/content/ShopAssist")
token = userdata.get("GITHUB_TOKEN")

if not token:
    raise ValueError("GITHUB_TOKEN is missing from Colab Secrets.")

# Use the token for this push only; do not print it.
remote_url = "https://github.com/DhruviPatadia/ShopAssist.git"
authenticated_url = remote_url.replace(
    "https://",
    f"https://x-access-token:{token}@"
)

result = subprocess.run(
    ["git", "push", authenticated_url, "HEAD:main"],
    cwd=project_dir,
    capture_output=True,
    text=True
)

print(result.stdout)
if result.stderr:
    print(result.stderr)

if result.returncode != 0:
    raise RuntimeError("Git push failed. Share the error with credentials removed.")

print("Push successful.")

In [ ]:
from pathlib import Path

project_dir = Path("/content/ShopAssist")
test_file = project_dir / "tests" / "test_retrieval_gemini.py"

test_code = r'''
import numpy as np
import pandas as pd
import pytest

from src.retrieval_gemini import (
    _embed_texts,
    search_policies,
    EMBEDDING_DIMENSIONS,
)


class FakeEmbedding:
    def __init__(self, values):
        self.values = values


class FakeResponse:
    def __init__(self, vectors):
        self.embeddings = [FakeEmbedding(v) for v in vectors]


class FakeModels:
    def __init__(self, vectors):
        self.vectors = vectors
        self.calls = []

    def embed_content(self, **kwargs):
        self.calls.append(kwargs)
        return FakeResponse(self.vectors)


class FakeClient:
    def __init__(self, vectors):
        self.models = FakeModels(vectors)


def test_embeddings_are_normalized():
    client = FakeClient([[3.0] + [0.0] * (EMBEDDING_DIMENSIONS - 1)])

    vectors = _embed_texts(client, ["test"], "RETRIEVAL_QUERY")

    assert vectors.shape == (1, EMBEDDING_DIMENSIONS)
    assert vectors.dtype == np.float32
    assert np.isclose(np.linalg.norm(vectors[0]), 1.0)


def test_empty_embedding_input():
    client = FakeClient([])

    vectors = _embed_texts(client, [], "RETRIEVAL_DOCUMENT")

    assert vectors.shape == (0, EMBEDDING_DIMENSIONS)
    assert not client.models.calls


def test_search_returns_matching_source_first():
    documents = pd.DataFrame({
        "source": ["returns_policy.md", "delivery_policy.md"],
        "text": ["Returns information", "Delivery information"],
    })

    query_vector = [1.0] + [0.0] * (EMBEDDING_DIMENSIONS - 1)
    other_vector = [0.0, 1.0] + [0.0] * (EMBEDDING_DIMENSIONS - 2)

    index_vectors = np.asarray(
        [query_vector, other_vector], dtype=np.float32
    )
    import faiss
    index = faiss.IndexFlatIP(EMBEDDING_DIMENSIONS)
    index.add(index_vectors)

    client = FakeClient([query_vector])

    results = search_policies(
        "How do returns work?", documents, client, index, top_k=2
    )

    assert results.iloc[0]["source"] == "returns_policy.md"
    assert len(results) == 2
    assert results.iloc[0]["similarity"] == pytest.approx(1.0)


def test_empty_query_returns_no_results():
    documents = pd.DataFrame({
        "source": ["returns_policy.md"],
        "text": ["Returns information"],
    })

    import faiss
    index = faiss.IndexFlatIP(EMBEDDING_DIMENSIONS)
    index.add(np.zeros((1, EMBEDDING_DIMENSIONS), dtype=np.float32))
    client = FakeClient([])

    results = search_policies("", documents, client, index)

    assert results.empty
    assert list(results.columns) == ["rank", "source", "similarity"]


def test_index_size_mismatch_raises_error():
    documents = pd.DataFrame({
        "source": ["returns_policy.md", "delivery_policy.md"],
        "text": ["Returns", "Delivery"],
    })

    import faiss
    index = faiss.IndexFlatIP(EMBEDDING_DIMENSIONS)
    index.add(np.zeros((1, EMBEDDING_DIMENSIONS), dtype=np.float32))
    client = FakeClient([])

    with pytest.raises(ValueError, match="Index size"):
        search_policies("returns", documents, client, index)
'''

test_file.write_text(test_code, encoding="utf-8")
print("Created:", test_file)

In [ ]:
import subprocess
import sys
from pathlib import Path

project_dir = Path("/content/ShopAssist")

result = subprocess.run(
    [
        sys.executable, "-m", "pytest",
        "tests/test_retrieval.py",
        "tests/test_retrieval_gemini.py",
        "-v"
    ],
    cwd=project_dir,
    capture_output=True,
    text=True
)

print(result.stdout)
if result.stderr:
    print(result.stderr)

print("Exit code:", result.returncode)

In [ ]:
import subprocess
from pathlib import Path

project_dir = Path("/content/ShopAssist")

# Stage only the new test file.
subprocess.run(
    ["git", "add", "tests/test_retrieval_gemini.py"],
    cwd=project_dir,
    check=True
)

# Commit the tests.
result = subprocess.run(
    ["git", "commit", "-m", "Add hosted embedding retrieval tests"],
    cwd=project_dir,
    capture_output=True,
    text=True
)

print(result.stdout)
if result.stderr:
    print(result.stderr)

if result.returncode != 0:
    raise RuntimeError("Commit failed. Please share the output.")

print("Test commit created.")

In [ ]:
import subprocess
from google.colab import userdata
from pathlib import Path

project_dir = Path("/content/ShopAssist")
token = userdata.get("GITHUB_TOKEN")

if not token:
    raise ValueError("GITHUB_TOKEN is missing from Colab Secrets.")

remote_url = "https://github.com/DhruviPatadia/ShopAssist.git"
authenticated_url = remote_url.replace(
    "https://",
    f"https://x-access-token:{token}@"
)

result = subprocess.run(
    ["git", "push", authenticated_url, "HEAD:main"],
    cwd=project_dir,
    capture_output=True,
    text=True
)

print(result.stdout)
if result.stderr:
    print(result.stderr)

if result.returncode != 0:
    raise RuntimeError("Push failed. Remove any credentials before sharing errors.")

print("Test file pushed successfully.")

In [ ]:
from pathlib import Path
import pandas as pd

project_dir = Path("/content/ShopAssist")
evaluation_file = (
    project_dir / "data" / "evaluation" / "evaluation_questions.csv"
)

questions_df = pd.read_csv(evaluation_file)

print("===== EXISTING EVALUATION DATASET =====")
print("Number of questions:", len(questions_df))
print("Columns:", questions_df.columns.tolist())

print("\n===== QUERY TYPE DISTRIBUTION =====")
print(questions_df["query_type"].value_counts(dropna=False))

print("\n===== EXPECTED SOURCE COVERAGE =====")
print(
    questions_df["expected_source"]
    .fillna("MISSING EXPECTED SOURCE")
    .value_counts()
)

print("\n===== MISSING VALUES =====")
print(questions_df.isna().sum())

print("\n===== ALL EXISTING QUESTIONS =====")
display(questions_df)